/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.theanasuddin.bros.classes;

import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.GraphicsEnvironment;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.util.Calendar;
import javax.swing.JOptionPane;
import jbl.javaDev.swingSupport.Carousel;

/**
 *
 * @author Anas
 */
public class DisplayOutput extends javax.swing.JFrame {

    Font poppinsSemiBold = null;
    Font poppinsSemiBold18 = null;
    Font poppinsRegular = null;
    Font poppinsLight14 = null;
    Font poppinsRegular18 = null;

    /**
     * Creates new form DisplayOutput
     */
    public DisplayOutput() {
        try {
            poppinsSemiBold = Font.createFont(Font.TRUETYPE_FONT, new File("src/com/theanasuddin/bros/fonts/PoppinsSemiBold.ttf")).deriveFont(20f);
            poppinsSemiBold18 = Font.createFont(Font.TRUETYPE_FONT, new File("src/com/theanasuddin/bros/fonts/PoppinsSemiBold.ttf")).deriveFont(18f);
            poppinsRegular = Font.createFont(Font.TRUETYPE_FONT, new File("src/com/theanasuddin/bros/fonts/PoppinsRegular.ttf")).deriveFont(16f);
            poppinsLight14 = Font.createFont(Font.TRUETYPE_FONT, new File("src/com/theanasuddin/bros/fonts/PoppinsLight.ttf")).deriveFont(14f);
            poppinsRegular18 = Font.createFont(Font.TRUETYPE_FONT, new File("src/com/theanasuddin/bros/fonts/PoppinsRegular.ttf")).deriveFont(18f);
            GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
            ge.registerFont(poppinsSemiBold);
            ge.registerFont(poppinsSemiBold18);
            ge.registerFont(poppinsRegular);
            ge.registerFont(poppinsLight14);
            ge.registerFont(poppinsRegular18);
        } catch (FontFormatException | IOException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        setIconImage(Toolkit.getDefaultToolkit().getImage(DisplayOutput.class.getResource("/com/theanasuddin/bros/images/icon.png")));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        pnlMealSummaryContainer = new javax.swing.JPanel();
        lblTotalUtilityBill = new javax.swing.JLabel();
        lblIndividualUtilityBill = new javax.swing.JLabel();
        lblIndividualUtility1 = new javax.swing.JLabel();
        lblHomeRent = new javax.swing.JLabel();
        lblTotalHomeRentValue = new javax.swing.JLabel();
        lblIndividualUtility2 = new javax.swing.JLabel();
        lblIndividualUtilityBillValue = new javax.swing.JLabel();
        lblTotalUtilityBillValue = new javax.swing.JLabel();
        lblAmount2 = new javax.swing.JLabel();
        lblBillType = new javax.swing.JLabel();
        spr2 = new javax.swing.JSeparator();
        lblUtilityBillLeft = new javax.swing.JLabel();
        lblUtilityBillRight = new javax.swing.JLabel();
        lblMealSummary = new javax.swing.JLabel();
        lblSummary = new javax.swing.JLabel();
        pnlNameHolder = new javax.swing.JPanel();
        lblSignature = new javax.swing.JLabel();
        lblLine = new javax.swing.JLabel();
        lblIndividualMealExpanses = new javax.swing.JLabel();
        spr3 = new javax.swing.JSeparator();
        lblAmount3 = new javax.swing.JLabel();
        lblName2 = new javax.swing.JLabel();
        lblIndividualUtilityBillLeft = new javax.swing.JLabel();
        lblIndividualUtilityBillRight = new javax.swing.JLabel();
        lblName3 = new javax.swing.JLabel();
        lblAmount6 = new javax.swing.JLabel();
        spr4 = new javax.swing.JSeparator();
        lblIndividualHomeRentUtilityBillLeft = new javax.swing.JLabel();
        lblIndividualHomeRentUtilityBillRight = new javax.swing.JLabel();
        lblName1 = new javax.swing.JLabel();
        lblAmount1 = new javax.swing.JLabel();
        spr1 = new javax.swing.JSeparator();
        lblHomeRentRight = new javax.swing.JLabel();
        lblHomeRentLeft = new javax.swing.JLabel();
        spr5 = new javax.swing.JSeparator();
        lblType1 = new javax.swing.JLabel();
        lblAmount4 = new javax.swing.JLabel();
        lblBazaarValue = new javax.swing.JLabel();
        lblBazaar = new javax.swing.JLabel();
        lblMeal = new javax.swing.JLabel();
        lblMealValue = new javax.swing.JLabel();
        lblMealRateValue = new javax.swing.JLabel();
        lblMealRate = new javax.swing.JLabel();
        lblHighestMeal = new javax.swing.JLabel();
        lblHighestMealValue = new javax.swing.JLabel();
        spr6 = new javax.swing.JSeparator();
        lblType2 = new javax.swing.JLabel();
        lblAmount5 = new javax.swing.JLabel();
        lblIndividualMealExpansesLeft = new javax.swing.JLabel();
        lblIndividualMealExpansesRight = new javax.swing.JLabel();
        pnlUtilityBillContainer = new Carousel();
        pnlHomeRentContainer = new Carousel();
        pnlIndividualUtilityBillContainer = new Carousel();
        pnlIndividualHomeRentUtilityBillContainer = new Carousel();
        pnlIndividualMealExpansesContainer = new Carousel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bros");
        setResizable(false);

        pnlMain.setPreferredSize(new java.awt.Dimension(960, 528));
        pnlMain.setLayout(null);

        pnlMealSummaryContainer.setBackground(new java.awt.Color(0,0,0,0));
        pnlMealSummaryContainer.setForeground(new java.awt.Color(255, 255, 255));
        pnlMealSummaryContainer.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pnlMealSummaryContainer.setPreferredSize(new java.awt.Dimension(150, 120));

        javax.swing.GroupLayout pnlMealSummaryContainerLayout = new javax.swing.GroupLayout(pnlMealSummaryContainer);
        pnlMealSummaryContainer.setLayout(pnlMealSummaryContainerLayout);
        pnlMealSummaryContainerLayout.setHorizontalGroup(
            pnlMealSummaryContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        pnlMealSummaryContainerLayout.setVerticalGroup(
            pnlMealSummaryContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        pnlMain.add(pnlMealSummaryContainer);
        pnlMealSummaryContainer.setBounds(90, 356, 150, 120);

        lblTotalUtilityBill.setFont(poppinsSemiBold);
        lblTotalUtilityBill.setForeground(new java.awt.Color(48, 213, 25));
        lblTotalUtilityBill.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalUtilityBill.setText("Total Utility Bill");
        lblTotalUtilityBill.setPreferredSize(new java.awt.Dimension(168, 28));
        pnlMain.add(lblTotalUtilityBill);
        lblTotalUtilityBill.setBounds(270, 65, 210, 20);

        lblIndividualUtilityBill.setFont(poppinsSemiBold);
        lblIndividualUtilityBill.setForeground(new java.awt.Color(48, 213, 25));
        lblIndividualUtilityBill.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIndividualUtilityBill.setText("Individual Utility Bill");
        lblIndividualUtilityBill.setPreferredSize(new java.awt.Dimension(168, 28));
        pnlMain.add(lblIndividualUtilityBill);
        lblIndividualUtilityBill.setBounds(480, 65, 210, 20);

        lblIndividualUtility1.setFont(poppinsSemiBold);
        lblIndividualUtility1.setForeground(new java.awt.Color(48, 213, 25));
        lblIndividualUtility1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIndividualUtility1.setText("Individual Home");
        lblIndividualUtility1.setPreferredSize(new java.awt.Dimension(168, 28));
        pnlMain.add(lblIndividualUtility1);
        lblIndividualUtility1.setBounds(690, 65, 210, 20);

        lblHomeRent.setFont(poppinsSemiBold);
        lblHomeRent.setForeground(new java.awt.Color(48, 213, 25));
        lblHomeRent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHomeRent.setText("Total Home Rent");
        lblHomeRent.setPreferredSize(new java.awt.Dimension(168, 28));
        pnlMain.add(lblHomeRent);
        lblHomeRent.setBounds(60, 65, 210, 20);

        lblTotalHomeRentValue.setFont(poppinsSemiBold18);
        lblTotalHomeRentValue.setForeground(new java.awt.Color(48, 213, 25));
        lblTotalHomeRentValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalHomeRentValue.setPreferredSize(new java.awt.Dimension(168, 28));
        pnlMain.add(lblTotalHomeRentValue);
        lblTotalHomeRentValue.setBounds(90, 90, 150, 20);

        lblIndividualUtility2.setFont(poppinsSemiBold18);
        lblIndividualUtility2.setForeground(new java.awt.Color(48, 213, 25));
        lblIndividualUtility2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIndividualUtility2.setText("Rent + Utility Bill");
        lblIndividualUtility2.setPreferredSize(new java.awt.Dimension(168, 28));
        pnlMain.add(lblIndividualUtility2);
        lblIndividualUtility2.setBounds(720, 90, 150, 20);

        lblIndividualUtilityBillValue.setFont(poppinsSemiBold18);
        lblIndividualUtilityBillValue.setForeground(new java.awt.Color(48, 213, 25));
        lblIndividualUtilityBillValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIndividualUtilityBillValue.setPreferredSize(new java.awt.Dimension(168, 28));
        pnlMain.add(lblIndividualUtilityBillValue);
        lblIndividualUtilityBillValue.setBounds(510, 90, 150, 20);

        lblTotalUtilityBillValue.setFont(poppinsSemiBold18);
        lblTotalUtilityBillValue.setForeground(new java.awt.Color(48, 213, 25));
        lblTotalUtilityBillValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalUtilityBillValue.setPreferredSize(new java.awt.Dimension(168, 28));
        pnlMain.add(lblTotalUtilityBillValue);
        lblTotalUtilityBillValue.setBounds(300, 90, 150, 20);

        lblAmount2.setFont(poppinsRegular);
        lblAmount2.setForeground(new java.awt.Color(255, 255, 255));
        lblAmount2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblAmount2.setText("Amount");
        pnlMain.add(lblAmount2);
        lblAmount2.setBounds(380, 120, 70, 16);

        lblBillType.setFont(poppinsRegular);
        lblBillType.setForeground(new java.awt.Color(255, 255, 255));
        lblBillType.setText("Bill Type");
        pnlMain.add(lblBillType);
        lblBillType.setBounds(300, 120, 70, 16);
        pnlMain.add(spr2);
        spr2.setBounds(300, 140, 150, 10);

        lblUtilityBillLeft.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUtilityBillLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/left.png"))); // NOI18N
        lblUtilityBillLeft.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblUtilityBillLeft.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblUtilityBillLeftMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblUtilityBillLeftMouseExited(evt);
            }
        });
        pnlMain.add(lblUtilityBillLeft);
        lblUtilityBillLeft.setBounds(275, 196, 20, 20);

        lblUtilityBillRight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUtilityBillRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/right.png"))); // NOI18N
        lblUtilityBillRight.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblUtilityBillRight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblUtilityBillRightMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblUtilityBillRightMouseExited(evt);
            }
        });
        pnlMain.add(lblUtilityBillRight);
        lblUtilityBillRight.setBounds(455, 196, 20, 20);

        lblMealSummary.setFont(poppinsSemiBold);
        lblMealSummary.setForeground(new java.awt.Color(48, 213, 25));
        lblMealSummary.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMealSummary.setText("Meal Summary");
        lblMealSummary.setPreferredSize(new java.awt.Dimension(168, 28));
        pnlMain.add(lblMealSummary);
        lblMealSummary.setBounds(60, 300, 210, 20);

        lblSummary.setFont(poppinsSemiBold);
        lblSummary.setForeground(new java.awt.Color(48, 213, 25));
        Calendar c = Calendar.getInstance();
        int monthNumber = c.get(Calendar.MONTH);
        int year = c.get(Calendar.YEAR);
        lblSummary.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        if("".equals(com.theanasuddin.bros.classes.GetBrosNumber.name)){
            lblSummary.setText("Dear, User! Your " + theMonth(monthNumber) + " " + year + " Calculation Summary");
        }
        else{
            com.theanasuddin.bros.classes.GetBrosNumber.name = com.theanasuddin.bros.classes.GetBrosNumber.name.substring(0, 1).toUpperCase() + com.theanasuddin.bros.classes.GetBrosNumber.name.substring(1).toLowerCase();
            lblSummary.setText("Dear, " + com.theanasuddin.bros.classes.GetBrosNumber.name + "! Your " + theMonth(monthNumber) + " " + year + " Calculation Summary");
        }
        lblSummary.setPreferredSize(new java.awt.Dimension(168, 28));
        pnlMain.add(lblSummary);
        lblSummary.setBounds(0, 15, 960, 30);

        pnlNameHolder.setBackground(new java.awt.Color (0,0,0,0));
        pnlNameHolder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout pnlNameHolderLayout = new javax.swing.GroupLayout(pnlNameHolder);
        pnlNameHolder.setLayout(pnlNameHolderLayout);
        pnlNameHolderLayout.setHorizontalGroup(
            pnlNameHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 148, Short.MAX_VALUE)
        );
        pnlNameHolderLayout.setVerticalGroup(
            pnlNameHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        pnlMain.add(pnlNameHolder);
        pnlNameHolder.setBounds(300, 333, 150, 30);

        lblSignature.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSignature.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/signature.png"))); // NOI18N
        pnlMain.add(lblSignature);
        lblSignature.setBounds(760, 360, 126, 74);

        lblLine.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/line.png"))); // NOI18N
        pnlMain.add(lblLine);
        lblLine.setBounds(840, 390, 68, 43);

        lblIndividualMealExpanses.setFont(poppinsSemiBold);
        lblIndividualMealExpanses.setForeground(new java.awt.Color(48, 213, 25));
        lblIndividualMealExpanses.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIndividualMealExpanses.setText("Individual M Expanses");
        lblIndividualMealExpanses.setPreferredSize(new java.awt.Dimension(168, 28));
        pnlMain.add(lblIndividualMealExpanses);
        lblIndividualMealExpanses.setBounds(240, 300, 270, 20);
        pnlMain.add(spr3);
        spr3.setBounds(510, 140, 150, 10);

        lblAmount3.setFont(poppinsRegular);
        lblAmount3.setForeground(new java.awt.Color(255, 255, 255));
        lblAmount3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblAmount3.setText("Amount");
        pnlMain.add(lblAmount3);
        lblAmount3.setBounds(590, 120, 70, 16);

        lblName2.setFont(poppinsRegular);
        lblName2.setForeground(new java.awt.Color(255, 255, 255));
        lblName2.setText("Name");
        pnlMain.add(lblName2);
        lblName2.setBounds(510, 120, 70, 16);

        lblIndividualUtilityBillLeft.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIndividualUtilityBillLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/left.png"))); // NOI18N
        lblIndividualUtilityBillLeft.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblIndividualUtilityBillLeft.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblIndividualUtilityBillLeftMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblIndividualUtilityBillLeftMouseExited(evt);
            }
        });
        pnlMain.add(lblIndividualUtilityBillLeft);
        lblIndividualUtilityBillLeft.setBounds(485, 196, 20, 20);

        lblIndividualUtilityBillRight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIndividualUtilityBillRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/right.png"))); // NOI18N
        lblIndividualUtilityBillRight.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblIndividualUtilityBillRight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblIndividualUtilityBillRightMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblIndividualUtilityBillRightMouseExited(evt);
            }
        });
        pnlMain.add(lblIndividualUtilityBillRight);
        lblIndividualUtilityBillRight.setBounds(665, 196, 20, 20);

        lblName3.setFont(poppinsRegular);
        lblName3.setForeground(new java.awt.Color(255, 255, 255));
        lblName3.setText("Name");
        pnlMain.add(lblName3);
        lblName3.setBounds(720, 120, 70, 16);

        lblAmount6.setFont(poppinsRegular);
        lblAmount6.setForeground(new java.awt.Color(255, 255, 255));
        lblAmount6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblAmount6.setText("Amount");
        pnlMain.add(lblAmount6);
        lblAmount6.setBounds(800, 120, 70, 16);
        pnlMain.add(spr4);
        spr4.setBounds(720, 140, 150, 10);

        lblIndividualHomeRentUtilityBillLeft.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIndividualHomeRentUtilityBillLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/left.png"))); // NOI18N
        lblIndividualHomeRentUtilityBillLeft.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblIndividualHomeRentUtilityBillLeft.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblIndividualHomeRentUtilityBillLeftMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblIndividualHomeRentUtilityBillLeftMouseExited(evt);
            }
        });
        pnlMain.add(lblIndividualHomeRentUtilityBillLeft);
        lblIndividualHomeRentUtilityBillLeft.setBounds(695, 196, 20, 20);

        lblIndividualHomeRentUtilityBillRight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIndividualHomeRentUtilityBillRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/right.png"))); // NOI18N
        lblIndividualHomeRentUtilityBillRight.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblIndividualHomeRentUtilityBillRight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblIndividualHomeRentUtilityBillRightMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblIndividualHomeRentUtilityBillRightMouseExited(evt);
            }
        });
        pnlMain.add(lblIndividualHomeRentUtilityBillRight);
        lblIndividualHomeRentUtilityBillRight.setBounds(875, 196, 20, 20);

        lblName1.setFont(poppinsRegular);
        lblName1.setForeground(new java.awt.Color(255, 255, 255));
        lblName1.setText("Name");
        pnlMain.add(lblName1);
        lblName1.setBounds(90, 120, 70, 16);

        lblAmount1.setFont(poppinsRegular);
        lblAmount1.setForeground(new java.awt.Color(255, 255, 255));
        lblAmount1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblAmount1.setText("Amount");
        pnlMain.add(lblAmount1);
        lblAmount1.setBounds(170, 120, 70, 16);
        pnlMain.add(spr1);
        spr1.setBounds(90, 140, 150, 10);

        lblHomeRentRight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHomeRentRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/right.png"))); // NOI18N
        lblHomeRentRight.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblHomeRentRight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblHomeRentRightMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblHomeRentRightMouseExited(evt);
            }
        });
        pnlMain.add(lblHomeRentRight);
        lblHomeRentRight.setBounds(245, 196, 20, 20);

        lblHomeRentLeft.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHomeRentLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/left.png"))); // NOI18N
        lblHomeRentLeft.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblHomeRentLeft.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblHomeRentLeftMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblHomeRentLeftMouseExited(evt);
            }
        });
        pnlMain.add(lblHomeRentLeft);
        lblHomeRentLeft.setBounds(65, 196, 20, 20);
        pnlMain.add(spr5);
        spr5.setBounds(90, 350, 150, 10);

        lblType1.setFont(poppinsRegular);
        lblType1.setForeground(new java.awt.Color(255, 255, 255));
        lblType1.setText("Type");
        pnlMain.add(lblType1);
        lblType1.setBounds(90, 330, 70, 16);

        lblAmount4.setFont(poppinsRegular);
        lblAmount4.setForeground(new java.awt.Color(255, 255, 255));
        lblAmount4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblAmount4.setText("Amount");
        pnlMain.add(lblAmount4);
        lblAmount4.setBounds(170, 330, 70, 16);

        lblBazaarValue.setFont(poppinsLight14);
        lblBazaarValue.setForeground(new java.awt.Color(255, 255, 255));
        lblBazaarValue.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        pnlMain.add(lblBazaarValue);
        lblBazaarValue.setBounds(170, 356, 70, 20);

        lblBazaar.setFont(poppinsLight14);
        lblBazaar.setForeground(new java.awt.Color(255, 255, 255));
        lblBazaar.setText("Bazaar");
        pnlMain.add(lblBazaar);
        lblBazaar.setBounds(90, 356, 70, 20);

        lblMeal.setFont(poppinsLight14);
        lblMeal.setForeground(new java.awt.Color(255, 255, 255));
        lblMeal.setText("Meal");
        pnlMain.add(lblMeal);
        lblMeal.setBounds(90, 381, 70, 20);

        lblMealValue.setFont(poppinsLight14);
        lblMealValue.setForeground(new java.awt.Color(255, 255, 255));
        lblMealValue.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        pnlMain.add(lblMealValue);
        lblMealValue.setBounds(170, 381, 70, 20);

        lblMealRateValue.setFont(poppinsLight14);
        lblMealRateValue.setForeground(new java.awt.Color(255, 255, 255));
        lblMealRateValue.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        pnlMain.add(lblMealRateValue);
        lblMealRateValue.setBounds(170, 406, 70, 20);

        lblMealRate.setFont(poppinsLight14);
        lblMealRate.setForeground(new java.awt.Color(255, 255, 255));
        lblMealRate.setText("Meal Rate");
        pnlMain.add(lblMealRate);
        lblMealRate.setBounds(90, 406, 70, 20);

        lblHighestMeal.setFont(poppinsLight14);
        lblHighestMeal.setForeground(new java.awt.Color(255, 255, 255));
        lblHighestMeal.setText("Highest M");
        pnlMain.add(lblHighestMeal);
        lblHighestMeal.setBounds(90, 431, 70, 20);

        lblHighestMealValue.setFont(poppinsLight14);
        lblHighestMealValue.setForeground(new java.awt.Color(255, 255, 255));
        lblHighestMealValue.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        pnlMain.add(lblHighestMealValue);
        lblHighestMealValue.setBounds(170, 431, 70, 20);
        pnlMain.add(spr6);
        spr6.setBounds(300, 390, 150, 10);

        lblType2.setFont(poppinsRegular);
        lblType2.setForeground(new java.awt.Color(255, 255, 255));
        lblType2.setText("Type");
        pnlMain.add(lblType2);
        lblType2.setBounds(300, 370, 70, 16);

        lblAmount5.setFont(poppinsRegular);
        lblAmount5.setForeground(new java.awt.Color(255, 255, 255));
        lblAmount5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblAmount5.setText("Amount");
        pnlMain.add(lblAmount5);
        lblAmount5.setBounds(380, 370, 70, 16);

        lblIndividualMealExpansesLeft.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIndividualMealExpansesLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/left.png"))); // NOI18N
        lblIndividualMealExpansesLeft.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblIndividualMealExpansesLeft.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblIndividualMealExpansesLeftMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblIndividualMealExpansesLeftMouseExited(evt);
            }
        });
        pnlMain.add(lblIndividualMealExpansesLeft);
        lblIndividualMealExpansesLeft.setBounds(275, 433, 20, 20);

        lblIndividualMealExpansesRight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIndividualMealExpansesRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/right.png"))); // NOI18N
        lblIndividualMealExpansesRight.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblIndividualMealExpansesRight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblIndividualMealExpansesRightMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblIndividualMealExpansesRightMouseExited(evt);
            }
        });
        pnlMain.add(lblIndividualMealExpansesRight);
        lblIndividualMealExpansesRight.setBounds(455, 433, 20, 20);

        pnlUtilityBillContainer.setBackground(new java.awt.Color(0,0,0,0));
        pnlUtilityBillContainer.setForeground(new java.awt.Color(255, 255, 255));
        pnlUtilityBillContainer.setPreferredSize(new java.awt.Dimension(150, 120));

        javax.swing.GroupLayout pnlUtilityBillContainerLayout = new javax.swing.GroupLayout(pnlUtilityBillContainer);
        pnlUtilityBillContainer.setLayout(pnlUtilityBillContainerLayout);
        pnlUtilityBillContainerLayout.setHorizontalGroup(
            pnlUtilityBillContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        pnlUtilityBillContainerLayout.setVerticalGroup(
            pnlUtilityBillContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        pnlMain.add(pnlUtilityBillContainer);
        pnlUtilityBillContainer.setBounds(300, 146, 150, 120);

        pnlHomeRentContainer.setBackground(new java.awt.Color(0,0,0,0));
        pnlHomeRentContainer.setForeground(new java.awt.Color(255, 255, 255));
        pnlHomeRentContainer.setPreferredSize(new java.awt.Dimension(150, 120));

        javax.swing.GroupLayout pnlHomeRentContainerLayout = new javax.swing.GroupLayout(pnlHomeRentContainer);
        pnlHomeRentContainer.setLayout(pnlHomeRentContainerLayout);
        pnlHomeRentContainerLayout.setHorizontalGroup(
            pnlHomeRentContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        pnlHomeRentContainerLayout.setVerticalGroup(
            pnlHomeRentContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        pnlMain.add(pnlHomeRentContainer);
        pnlHomeRentContainer.setBounds(90, 146, 150, 120);

        pnlIndividualUtilityBillContainer.setBackground(new java.awt.Color(0,0,0,0));
        pnlIndividualUtilityBillContainer.setForeground(new java.awt.Color(255, 255, 255));
        pnlIndividualUtilityBillContainer.setPreferredSize(new java.awt.Dimension(150, 120));

        javax.swing.GroupLayout pnlIndividualUtilityBillContainerLayout = new javax.swing.GroupLayout(pnlIndividualUtilityBillContainer);
        pnlIndividualUtilityBillContainer.setLayout(pnlIndividualUtilityBillContainerLayout);
        pnlIndividualUtilityBillContainerLayout.setHorizontalGroup(
            pnlIndividualUtilityBillContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        pnlIndividualUtilityBillContainerLayout.setVerticalGroup(
            pnlIndividualUtilityBillContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        pnlMain.add(pnlIndividualUtilityBillContainer);
        pnlIndividualUtilityBillContainer.setBounds(510, 146, 150, 120);

        pnlIndividualHomeRentUtilityBillContainer.setBackground(new java.awt.Color(0,0,0,0));
        pnlIndividualHomeRentUtilityBillContainer.setForeground(new java.awt.Color(255, 255, 255));
        pnlIndividualHomeRentUtilityBillContainer.setPreferredSize(new java.awt.Dimension(150, 120));

        javax.swing.GroupLayout pnlIndividualHomeRentUtilityBillContainerLayout = new javax.swing.GroupLayout(pnlIndividualHomeRentUtilityBillContainer);
        pnlIndividualHomeRentUtilityBillContainer.setLayout(pnlIndividualHomeRentUtilityBillContainerLayout);
        pnlIndividualHomeRentUtilityBillContainerLayout.setHorizontalGroup(
            pnlIndividualHomeRentUtilityBillContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        pnlIndividualHomeRentUtilityBillContainerLayout.setVerticalGroup(
            pnlIndividualHomeRentUtilityBillContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        pnlMain.add(pnlIndividualHomeRentUtilityBillContainer);
        pnlIndividualHomeRentUtilityBillContainer.setBounds(720, 146, 150, 120);

        pnlIndividualMealExpansesContainer.setBackground(new java.awt.Color(0,0,0,0));
        pnlIndividualMealExpansesContainer.setForeground(new java.awt.Color(255, 255, 255));
        pnlIndividualMealExpansesContainer.setPreferredSize(new java.awt.Dimension(150, 158));

        javax.swing.GroupLayout pnlIndividualMealExpansesContainerLayout = new javax.swing.GroupLayout(pnlIndividualMealExpansesContainer);
        pnlIndividualMealExpansesContainer.setLayout(pnlIndividualMealExpansesContainerLayout);
        pnlIndividualMealExpansesContainerLayout.setHorizontalGroup(
            pnlIndividualMealExpansesContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        pnlIndividualMealExpansesContainerLayout.setVerticalGroup(
            pnlIndividualMealExpansesContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 158, Short.MAX_VALUE)
        );

        pnlMain.add(pnlIndividualMealExpansesContainer);
        pnlIndividualMealExpansesContainer.setBounds(300, 333, 150, 158);

        lblBackground.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/jar.jpg"))); // NOI18N
        pnlMain.add(lblBackground);
        lblBackground.setBounds(0, 0, 960, 528);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblUtilityBillLeftMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUtilityBillLeftMouseEntered
        // TODO add your handling code here:
        lblUtilityBillLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/left_hover.png")));
    }//GEN-LAST:event_lblUtilityBillLeftMouseEntered

    private void lblUtilityBillLeftMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUtilityBillLeftMouseExited
        // TODO add your handling code here:
        lblUtilityBillLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/left.png")));
    }//GEN-LAST:event_lblUtilityBillLeftMouseExited

    private void lblUtilityBillRightMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUtilityBillRightMouseExited
        // TODO add your handling code here:
        lblUtilityBillRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/right.png")));
    }//GEN-LAST:event_lblUtilityBillRightMouseExited

    private void lblUtilityBillRightMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUtilityBillRightMouseEntered
        // TODO add your handling code here:
        lblUtilityBillRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/right_hover.png")));
    }//GEN-LAST:event_lblUtilityBillRightMouseEntered

    private void lblHomeRentLeftMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeRentLeftMouseEntered
        // TODO add your handling code here:
        lblHomeRentLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/left_hover.png")));
    }//GEN-LAST:event_lblHomeRentLeftMouseEntered

    private void lblHomeRentLeftMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeRentLeftMouseExited
        // TODO add your handling code here:
        lblHomeRentLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/left.png")));
    }//GEN-LAST:event_lblHomeRentLeftMouseExited

    private void lblHomeRentRightMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeRentRightMouseEntered
        // TODO add your handling code here:
        lblHomeRentRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/right_hover.png")));
    }//GEN-LAST:event_lblHomeRentRightMouseEntered

    private void lblHomeRentRightMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeRentRightMouseExited
        // TODO add your handling code here:
        lblHomeRentRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/right.png")));
    }//GEN-LAST:event_lblHomeRentRightMouseExited

    private void lblIndividualUtilityBillLeftMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIndividualUtilityBillLeftMouseEntered
        // TODO add your handling code here:
        lblIndividualUtilityBillLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/left_hover.png")));
    }//GEN-LAST:event_lblIndividualUtilityBillLeftMouseEntered

    private void lblIndividualUtilityBillLeftMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIndividualUtilityBillLeftMouseExited
        // TODO add your handling code here:
        lblIndividualUtilityBillLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/left.png")));
    }//GEN-LAST:event_lblIndividualUtilityBillLeftMouseExited

    private void lblIndividualUtilityBillRightMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIndividualUtilityBillRightMouseEntered
        // TODO add your handling code here:
        lblIndividualUtilityBillRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/right_hover.png")));
    }//GEN-LAST:event_lblIndividualUtilityBillRightMouseEntered

    private void lblIndividualUtilityBillRightMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIndividualUtilityBillRightMouseExited
        // TODO add your handling code here:
        lblIndividualUtilityBillRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/right.png")));
    }//GEN-LAST:event_lblIndividualUtilityBillRightMouseExited

    private void lblIndividualHomeRentUtilityBillLeftMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIndividualHomeRentUtilityBillLeftMouseEntered
        // TODO add your handling code here:
        lblIndividualHomeRentUtilityBillLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/left_hover.png")));

    }//GEN-LAST:event_lblIndividualHomeRentUtilityBillLeftMouseEntered

    private void lblIndividualHomeRentUtilityBillLeftMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIndividualHomeRentUtilityBillLeftMouseExited
        // TODO add your handling code here:
        lblIndividualHomeRentUtilityBillLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/left.png")));

    }//GEN-LAST:event_lblIndividualHomeRentUtilityBillLeftMouseExited

    private void lblIndividualHomeRentUtilityBillRightMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIndividualHomeRentUtilityBillRightMouseEntered
        // TODO add your handling code here:
        lblIndividualHomeRentUtilityBillRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/right_hover.png")));

    }//GEN-LAST:event_lblIndividualHomeRentUtilityBillRightMouseEntered

    private void lblIndividualHomeRentUtilityBillRightMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIndividualHomeRentUtilityBillRightMouseExited
        // TODO add your handling code here:
        lblIndividualHomeRentUtilityBillRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/right.png")));

    }//GEN-LAST:event_lblIndividualHomeRentUtilityBillRightMouseExited

    private void lblIndividualMealExpansesLeftMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIndividualMealExpansesLeftMouseEntered
        // TODO add your handling code here:
        lblIndividualMealExpansesLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/left_hover.png")));
    }//GEN-LAST:event_lblIndividualMealExpansesLeftMouseEntered

    private void lblIndividualMealExpansesLeftMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIndividualMealExpansesLeftMouseExited
        // TODO add your handling code here:
        lblIndividualMealExpansesLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/left.png")));

    }//GEN-LAST:event_lblIndividualMealExpansesLeftMouseExited

    private void lblIndividualMealExpansesRightMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIndividualMealExpansesRightMouseEntered
        // TODO add your handling code here:
        lblIndividualMealExpansesRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/right_hover.png")));

    }//GEN-LAST:event_lblIndividualMealExpansesRightMouseEntered

    private void lblIndividualMealExpansesRightMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIndividualMealExpansesRightMouseExited
        // TODO add your handling code here:
        lblIndividualMealExpansesRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/right.png")));

    }//GEN-LAST:event_lblIndividualMealExpansesRightMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisplayOutput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisplayOutput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisplayOutput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisplayOutput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DisplayOutput().setVisible(true);
            }
        });
    }

    static String theMonth(int month) {
        String[] monthNames = {"January", "February", "March", "April", "May", "June", "July", "August", "September",
            "October", "November", "December"};
        return monthNames[month];
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAmount1;
    private javax.swing.JLabel lblAmount2;
    private javax.swing.JLabel lblAmount3;
    private javax.swing.JLabel lblAmount4;
    private javax.swing.JLabel lblAmount5;
    private javax.swing.JLabel lblAmount6;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblBazaar;
    public javax.swing.JLabel lblBazaarValue;
    private javax.swing.JLabel lblBillType;
    private javax.swing.JLabel lblHighestMeal;
    public javax.swing.JLabel lblHighestMealValue;
    private javax.swing.JLabel lblHomeRent;
    public javax.swing.JLabel lblHomeRentLeft;
    public javax.swing.JLabel lblHomeRentRight;
    public javax.swing.JLabel lblIndividualHomeRentUtilityBillLeft;
    public javax.swing.JLabel lblIndividualHomeRentUtilityBillRight;
    private javax.swing.JLabel lblIndividualMealExpanses;
    public javax.swing.JLabel lblIndividualMealExpansesLeft;
    public javax.swing.JLabel lblIndividualMealExpansesRight;
    private javax.swing.JLabel lblIndividualUtility1;
    private javax.swing.JLabel lblIndividualUtility2;
    private javax.swing.JLabel lblIndividualUtilityBill;
    public javax.swing.JLabel lblIndividualUtilityBillLeft;
    public javax.swing.JLabel lblIndividualUtilityBillRight;
    public javax.swing.JLabel lblIndividualUtilityBillValue;
    private javax.swing.JLabel lblLine;
    private javax.swing.JLabel lblMeal;
    private javax.swing.JLabel lblMealRate;
    public javax.swing.JLabel lblMealRateValue;
    private javax.swing.JLabel lblMealSummary;
    public javax.swing.JLabel lblMealValue;
    private javax.swing.JLabel lblName1;
    private javax.swing.JLabel lblName2;
    private javax.swing.JLabel lblName3;
    private javax.swing.JLabel lblSignature;
    private javax.swing.JLabel lblSummary;
    public javax.swing.JLabel lblTotalHomeRentValue;
    private javax.swing.JLabel lblTotalUtilityBill;
    public javax.swing.JLabel lblTotalUtilityBillValue;
    private javax.swing.JLabel lblType1;
    private javax.swing.JLabel lblType2;
    public javax.swing.JLabel lblUtilityBillLeft;
    public javax.swing.JLabel lblUtilityBillRight;
    /*
    public javax.swing.JPanel pnlHomeRentContainer;
    public Carousel pnlUtilityBillContainer;
    */
    public Carousel pnlHomeRentContainer;
    /*
    public javax.swing.JPanel pnlIndividualHomeRentUtilityBillContainer;
    public Carousel pnlUtilityBillContainer;
    public Carousel pnlHomeRentContainer;
    public Carousel pnlIndividualUtilityBillContainer;
    */
    public Carousel pnlIndividualHomeRentUtilityBillContainer;
    /*
    public javax.swing.JPanel pnlIndividualMealExpansesContainer;
    public Carousel pnlUtilityBillContainer;
    public Carousel pnlHomeRentContainer;
    */
    public Carousel pnlIndividualMealExpansesContainer;
    /*
    public javax.swing.JPanel pnlIndividualUtilityBillContainer;
    public Carousel pnlUtilityBillContainer;
    public Carousel pnlHomeRentContainer;
    */
    public Carousel pnlIndividualUtilityBillContainer;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlMealSummaryContainer;
    private javax.swing.JPanel pnlNameHolder;
    /*
    public javax.swing.JPanel pnlUtilityBillContainer;
    */
    public Carousel pnlUtilityBillContainer;
    private javax.swing.JSeparator spr1;
    private javax.swing.JSeparator spr2;
    private javax.swing.JSeparator spr3;
    private javax.swing.JSeparator spr4;
    private javax.swing.JSeparator spr5;
    private javax.swing.JSeparator spr6;
    // End of variables declaration//GEN-END:variables
}
