/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.theanasuddin.bros.classes;

import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.GraphicsEnvironment;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Anas
 */
public class GetBrosNumber extends javax.swing.JFrame {

    /**
     * Creates new form GetBrosNumberWindow
     */
    Font poppinsSemiBold = null;
    Font poppinsExtraLight = null;
    Font poppinsThin = null;

    public GetBrosNumber() {
        try {
            poppinsSemiBold = Font.createFont(Font.TRUETYPE_FONT, new File("src/com/theanasuddin/bros/fonts/PoppinsSemiBold.ttf")).deriveFont(20f);
            poppinsExtraLight = Font.createFont(Font.TRUETYPE_FONT, new File("src/com/theanasuddin/bros/fonts/PoppinsSemiBold.ttf")).deriveFont(15f);
            poppinsThin = Font.createFont(Font.TRUETYPE_FONT, new File("src/com/theanasuddin/bros/fonts/PoppinsThin.ttf")).deriveFont(15f);
            GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
            ge.registerFont(poppinsSemiBold);
            ge.registerFont(poppinsExtraLight);
            ge.registerFont(poppinsThin);
        } catch (FontFormatException | IOException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        setIconImage(Toolkit.getDefaultToolkit().getImage(GetBrosNumber.class.getResource("/com/theanasuddin/bros/images/icon.png")));

        c = Calendar.getInstance();
        lblGreetingTimeHidden = new javax.swing.JLabel();
        timeOfDay = c.get(Calendar.HOUR_OF_DAY);
        if (timeOfDay >= 0 && timeOfDay < 12) {
            lblGreetingTimeHidden.setText("Good Morning!");
        } else if (timeOfDay >= 12 && timeOfDay < 16) {
            lblGreetingTimeHidden.setText("Good Afternoon!");
        } else if (timeOfDay >= 16 && timeOfDay < 21) {
            lblGreetingTimeHidden.setText("Good Evening!");
        } else if (timeOfDay >= 21 && timeOfDay < 24) {
            lblGreetingTimeHidden.setText("Good Night!");
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        lblInputField2 = new javax.swing.JLabel();
        lblInputField1 = new javax.swing.JLabel();
        txtInputField1 = new javax.swing.JTextField();
        txtInputField1Disabled = new javax.swing.JTextField();
        txtInputField2 = new javax.swing.JTextField();
        txtInputField2Disabled = new javax.swing.JTextField();
        lblSmile = new javax.swing.JLabel();
        lblWelcome = new javax.swing.JLabel();
        lblGo = new javax.swing.JLabel();
        lblCancel = new javax.swing.JLabel();
        lblGreetingTime = lblGreetingTimeHidden;
        lblBackGroundImage = new javax.swing.JLabel();
        lblGreetingTimeHidden = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Bros");
        setName("GetBrosNumberWindow"); // NOI18N
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        pnlMain.setPreferredSize(new java.awt.Dimension(528, 528));
        pnlMain.setLayout(null);

        lblInputField2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblInputField2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/input_field_1.png")));
        lblInputField2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pnlMain.add(lblInputField2);
        lblInputField2.setBounds(60, 268, 410, 52);

        lblInputField1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblInputField1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/input_field_1.png")));
        lblInputField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pnlMain.add(lblInputField1);
        lblInputField1.setBounds(60, 208, 410, 52);

        txtInputField1.setBackground(new Color(0,0,0,0));
        txtInputField1.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txtInputField1.setForeground(new java.awt.Color(235,234,237));
        txtInputField1.setBorder(null);
        txtInputField1.setSelectedTextColor(new Color(255,255,255));
        txtInputField1.setSelectionColor(new Color(48,213,25));
        txtInputField1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtInputField1CaretUpdate(evt);
            }
        });
        txtInputField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtInputField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtInputField1FocusLost(evt);
            }
        });
        txtInputField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtInputField1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtInputField1KeyTyped(evt);
            }
        });
        pnlMain.add(txtInputField1);
        txtInputField1.setBounds(70, 210, 390, 52);

        txtInputField1Disabled.setBackground(new Color(0,0,0,0));
        txtInputField1Disabled.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txtInputField1Disabled.setText("How many members?");
        txtInputField1Disabled.setBorder(null);
        txtInputField1Disabled.setCaretPosition(0);
        txtInputField1Disabled.setDisabledTextColor(new Color(149,150,156));
        txtInputField1Disabled.setEnabled(false);
        pnlMain.add(txtInputField1Disabled);
        txtInputField1Disabled.setBounds(70, 210, 390, 52);

        txtInputField2.setBackground(new Color(0,0,0,0));
        txtInputField2.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txtInputField2.setForeground(new java.awt.Color(235,234,237));
        txtInputField2.setBorder(null);
        txtInputField2.setPreferredSize(new java.awt.Dimension(144, 18));
        txtInputField2.setSelectedTextColor(new Color(255,255,255));
        txtInputField2.setSelectionColor(new Color(48,213,25));
        txtInputField2.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtInputField2CaretUpdate(evt);
            }
        });
        txtInputField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtInputField2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtInputField2FocusLost(evt);
            }
        });
        txtInputField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtInputField2KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtInputField2KeyTyped(evt);
            }
        });
        pnlMain.add(txtInputField2);
        txtInputField2.setBounds(70, 270, 390, 52);

        txtInputField2Disabled.setBackground(new Color(0,0,0,0));
        txtInputField2Disabled.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txtInputField2Disabled.setText("Enter your name");
        txtInputField2Disabled.setBorder(null);
        txtInputField2Disabled.setCaretPosition(0);
        txtInputField2Disabled.setDisabledTextColor(new Color(149,150,156));
        txtInputField2Disabled.setEnabled(false);
        txtInputField2Disabled.setPreferredSize(new java.awt.Dimension(144, 18));
        pnlMain.add(txtInputField2Disabled);
        txtInputField2Disabled.setBounds(70, 270, 390, 52);

        lblSmile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/smile.png")));
        pnlMain.add(lblSmile);
        lblSmile.setBounds(180, 98, 20, 20);

        lblWelcome.setFont(poppinsSemiBold);
        lblWelcome.setForeground(new java.awt.Color(255, 255, 255));
        lblWelcome.setText("Welcome!");
        pnlMain.add(lblWelcome);
        lblWelcome.setBounds(60, 100, 110, 16);

        lblGo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/go_button.png")));
        lblGo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGoMouseClicked(evt);
            }
        });
        pnlMain.add(lblGo);
        lblGo.setBounds(378, 380, 92, 34);

        lblCancel.setBackground(new Color(0,0,0,0));
        lblCancel.setForeground(new Color(0,0,0,0));
        lblCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/cancel_button.png")));
        lblCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCancel.setFocusable(false);
        lblCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCancelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCancelMouseExited(evt);
            }
        });
        pnlMain.add(lblCancel);
        lblCancel.setBounds(380, 380, 0, 0);

        lblGreetingTime.setFont(poppinsSemiBold);
        lblGreetingTime.setForeground(new java.awt.Color(255, 255, 255));
        lblGreetingTime.setPreferredSize(new java.awt.Dimension(84, 16));
        pnlMain.add(lblGreetingTime);
        lblGreetingTime.setBounds(60, 125, 170, 23);

        lblBackGroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/cherries.png")));
        lblBackGroundImage.setPreferredSize(new java.awt.Dimension(528, 528));
        pnlMain.add(lblBackGroundImage);
        lblBackGroundImage.setBounds(0, 0, 528, 528);
        pnlMain.add(lblGreetingTimeHidden);
        lblGreetingTimeHidden.setBounds(370, 70, 0, 0);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblCancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancelMouseExited
        // TODO add your handling code here:
        lblCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/cancel_button.png")));
    }//GEN-LAST:event_lblCancelMouseExited

    private void lblCancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancelMouseEntered
        // TODO add your handling code here:
        lblCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/cancel_button_hover.png")));
    }//GEN-LAST:event_lblCancelMouseEntered

    private void txtInputField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtInputField2FocusGained
        // TODO add your handling code here:
        if ("".equals(txtInputField2.getText())) {
            lblInputField2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/input_field_1_focused.png")));

        } else {
            lblInputField2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/input_field_1_focused_type.png")));
        }
    }//GEN-LAST:event_txtInputField2FocusGained

    private void txtInputField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtInputField2FocusLost
        // TODO add your handling code here:
        lblInputField2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/input_field_1.png")));
    }//GEN-LAST:event_txtInputField2FocusLost

    private void txtInputField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtInputField1FocusGained
        // TODO add your handling code here:
        if ("".equals(txtInputField1.getText())) {
            lblInputField1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/input_field_1_focused.png")));

        } else {
            lblInputField1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/input_field_0_focused_type.png")));
        }
    }//GEN-LAST:event_txtInputField1FocusGained

    private void txtInputField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtInputField1FocusLost
        // TODO add your handling code here:
        lblInputField1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/input_field_1.png")));
    }//GEN-LAST:event_txtInputField1FocusLost

    private void lblCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancelMouseClicked
        this.dispose();
    }//GEN-LAST:event_lblCancelMouseClicked

    private void txtInputField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInputField1KeyTyped
        // TODO add your handling code here:
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {
            lblInputField1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/input_field_0_focused_type.png")));
        }

    }//GEN-LAST:event_txtInputField1KeyTyped

    private void txtInputField1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtInputField1CaretUpdate
        // TODO add your handling code here:
        if (txtInputField1.getText().length() != 0) {
            txtInputField1Disabled.setVisible(false);
            if (txtInputField2OK) {
                try {
                    if (Integer.parseInt(txtInputField1.getText().trim().replaceAll(" +", "")) > 0) {
                        lblGo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/go_button_activated.png")));
                        lblGo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                        lblGoEnabled = true; 
                        numberOfMembersField = Integer.parseInt(txtInputField1.getText().trim().replaceAll(" +", ""));
                        txtInputField1OK = true;

                    } else if (Integer.parseInt(txtInputField1.getText().trim().replaceAll(" +", "")) <= 0) {
                        lblGo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/go_button.png")));
                        lblGo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                        lblGoEnabled = false;
                        txtInputField1OK = false;

                    }
                } catch (Exception e) {

                }
            }
        } else {
            txtInputField1Disabled.setVisible(true);
        }

        if (txtInputField1.getText().length() == 0) {
            lblGo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/go_button.png")));
            lblGo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            lblGoEnabled = false;
            txtInputField1OK = false;
        }
    }//GEN-LAST:event_txtInputField1CaretUpdate

    private void lblGoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGoMouseClicked
        // TODO add your handling code here:
        if (lblGoEnabled) {
            if (txtInputField2.getText().trim().equals(name)) {
                this.dispose();
                numberOfMembers = numberOfMembersField;
                if (i <= numberOfMembers) {

                    if (i % 100 >= 11 && i % 100 <= 20) {
                        ordinal = i + "th";
                    } else if (i % 10 == 1) {
                        ordinal = i + "st";
                    } else if (i % 10 == 2) {
                        ordinal = i + "nd";
                    } else if (i % 10 == 3) {
                        ordinal = i + "rd";
                    } else {
                        ordinal = i + "th";
                    }

                    GetBrosDetails firstBro = new GetBrosDetails(ordinal, i);
                    firstBro.setVisible(true);
                }

            } else if(txtInputField2.getText().trim().replaceAll(" +", "").length() != 0) {
                this.dispose();
                name = txtInputField2.getText().trim().replaceAll(" +", " ");
                name = name.substring(0, 1).toUpperCase() + name.substring(1).toLowerCase();
                numberOfMembers = numberOfMembersField;
                if (i <= numberOfMembers) {

                    if (i % 100 >= 11 && i % 100 <= 20) {
                        ordinal = i + "th";
                    } else if (i % 10 == 1) {
                        ordinal = i + "st";
                    } else if (i % 10 == 2) {
                        ordinal = i + "nd";
                    } else if (i % 10 == 3) {
                        ordinal = i + "rd";
                    } else {
                        ordinal = i + "th";
                    }
                    GetBrosDetails firstBro = new GetBrosDetails(ordinal, i);
                    firstBro.setVisible(true);
                }

            }
        }
    }//GEN-LAST:event_lblGoMouseClicked

    private void txtInputField2CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtInputField2CaretUpdate
        // TODO add your handling code here:
        if (txtInputField2.getText().length() != 0) {
            txtInputField2Disabled.setVisible(false);
            if (txtInputField1OK) {
                try {
                    if (validateString(txtInputField2.getText().trim().replaceAll(" +", "")) == true) {
                        lblGo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/go_button_activated.png")));
                        lblGo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                        lblGoEnabled = true;
                        txtInputField2OK = true;
                        name = txtInputField2.getText().trim().replaceAll(" +", " ");

                    } else if (validateString(txtInputField2.getText().trim().replaceAll(" +", "")) == false) {
                        lblGo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/go_button.png")));
                        lblGo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                        lblGoEnabled = false;
                        txtInputField2OK = false;

                    }
                } catch (Exception e) {

                }
            }
        } else {
            txtInputField2Disabled.setVisible(true);
        }

        if (txtInputField2.getText().trim().length() == 0 && txtInputField1OK) {
            lblGo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/go_button_activated.png")));
            lblGo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            lblGoEnabled = true;
        }
    }//GEN-LAST:event_txtInputField2CaretUpdate

    private void txtInputField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInputField2KeyTyped
        // TODO add your handling code here:
        if (Character.isLetter(evt.getKeyChar())) {
            lblInputField2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/input_field_1_focused_type.png")));
        }


    }//GEN-LAST:event_txtInputField2KeyTyped

    private void txtInputField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInputField1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' || Character.isISOControl(evt.getKeyChar())
                || (evt.getKeyCode() == KeyEvent.VK_CONTROL) || (evt.getKeyCode() == KeyEvent.VK_SHIFT) || (evt.getKeyCode() == KeyEvent.VK_CAPS_LOCK)
                || (evt.getKeyCode() == KeyEvent.VK_COMMAND) || (evt.getKeyCode() == KeyEvent.VK_WINDOWS) || (evt.getKeyCode() == KeyEvent.VK_ALT)
                || (evt.getKeyCode() == KeyEvent.VK_ALT_GRAPH) || (evt.getKeyCode() == KeyEvent.VK_NUM_LOCK) || (evt.getKeyCode() == KeyEvent.VK_HOME)
                || (evt.getKeyCode() == KeyEvent.VK_END) || (evt.getKeyCode() == KeyEvent.VK_LEFT) || (evt.getKeyCode() == KeyEvent.VK_RIGHT)) {
            txtInputField1.setEditable(true);
        } else {
            txtInputField1.setEditable(false);
            getToolkit().beep();

        }

    }//GEN-LAST:event_txtInputField1KeyPressed

    private void txtInputField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInputField2KeyPressed
        // TODO add your handling code here:
        if (Character.isLetter(evt.getKeyChar()) || Character.isISOControl(evt.getKeyChar()) || Character.isWhitespace(evt.getKeyChar())
                || (evt.getKeyCode() == KeyEvent.VK_CONTROL) || (evt.getKeyCode() == KeyEvent.VK_SHIFT) || (evt.getKeyCode() == KeyEvent.VK_CAPS_LOCK)
                || (evt.getKeyCode() == KeyEvent.VK_COMMAND) || (evt.getKeyCode() == KeyEvent.VK_WINDOWS) || (evt.getKeyCode() == KeyEvent.VK_ALT)
                || (evt.getKeyCode() == KeyEvent.VK_ALT_GRAPH) || (evt.getKeyCode() == KeyEvent.VK_NUM_LOCK) || (evt.getKeyCode() == KeyEvent.VK_HOME)
                || (evt.getKeyCode() == KeyEvent.VK_END) || (evt.getKeyCode() == KeyEvent.VK_LEFT) || (evt.getKeyCode() == KeyEvent.VK_RIGHT)) {
            txtInputField2.setEditable(true);

        } else {
            txtInputField2.setEditable(false);
            getToolkit().beep();
        }
    }//GEN-LAST:event_txtInputField2KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GetBrosNumber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GetBrosNumber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GetBrosNumber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GetBrosNumber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                GetBrosNumber object = new GetBrosNumber();
                object.setVisible(true);

            }
        });
    }
    static int timeOfDay;
    static Calendar c;
    static String name = "";
    static boolean lblGoEnabled = false;  //txtInputField2
    static int numberOfMembers;
    static int numberOfMembersField;
    static String ordinal = "";
    static int i = 1;
    static boolean txtInputField1OK = false;
    static boolean txtInputField2OK = true;

    public boolean validateString(String str) {
        str = str.toLowerCase();
        char[] charArray = str.toCharArray();
        for (int i = 0; i < charArray.length; i++) {
            char ch = charArray[i];
            if (!(ch >= 'a' && ch <= 'z')) {
                return false;
            }
        }
        return true;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBackGroundImage;
    private javax.swing.JLabel lblCancel;
    private javax.swing.JLabel lblGo;
    private static javax.swing.JLabel lblGreetingTime;
    private static javax.swing.JLabel lblGreetingTimeHidden;
    private javax.swing.JLabel lblInputField1;
    private javax.swing.JLabel lblInputField2;
    private javax.swing.JLabel lblSmile;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JTextField txtInputField1;
    private javax.swing.JTextField txtInputField1Disabled;
    private javax.swing.JTextField txtInputField2;
    private javax.swing.JTextField txtInputField2Disabled;
    // End of variables declaration//GEN-END:variables
}
