/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.theanasuddin.bros.classes;

import com.sun.glass.events.KeyEvent;
import static com.theanasuddin.bros.classes.GetBrosNumber.ordinal;
import java.awt.Color;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.GraphicsEnvironment;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Anas
 */
public class GetBrosDetails extends javax.swing.JFrame {

    Font poppinsSemiBold = null;
    Font poppinsExtraLight = null;
    Font poppinsThin = null;

    /**
     * Creates new form GetBrosDetails
     */
    public GetBrosDetails() {
        try {
            poppinsSemiBold = Font.createFont(Font.TRUETYPE_FONT, new File("src/com/theanasuddin/bros/fonts/PoppinsSemiBold.ttf")).deriveFont(20f);
            poppinsExtraLight = Font.createFont(Font.TRUETYPE_FONT, new File("src/com/theanasuddin/bros/fonts/PoppinsSemiBold.ttf")).deriveFont(15f);
            poppinsThin = Font.createFont(Font.TRUETYPE_FONT, new File("src/com/theanasuddin/bros/fonts/PoppinsThin.ttf")).deriveFont(15f);
            GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
            ge.registerFont(poppinsSemiBold);
            ge.registerFont(poppinsExtraLight);
            ge.registerFont(poppinsThin);
        } catch (FontFormatException | IOException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        setIconImage(Toolkit.getDefaultToolkit().getImage(GetBrosDetails.class.getResource("/com/theanasuddin/bros/images/icon.png")));
        initComponents();
    }

    public GetBrosDetails(String ordinal, int i) {
        try {
            poppinsSemiBold = Font.createFont(Font.TRUETYPE_FONT, new File("src/com/theanasuddin/bros/fonts/PoppinsSemiBold.ttf")).deriveFont(20f);
            poppinsExtraLight = Font.createFont(Font.TRUETYPE_FONT, new File("src/com/theanasuddin/bros/fonts/PoppinsSemiBold.ttf")).deriveFont(15f);
            poppinsThin = Font.createFont(Font.TRUETYPE_FONT, new File("src/com/theanasuddin/bros/fonts/PoppinsThin.ttf")).deriveFont(15f);
            GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
            ge.registerFont(poppinsSemiBold);
            ge.registerFont(poppinsExtraLight);
            ge.registerFont(poppinsThin);
        } catch (FontFormatException | IOException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        serial = ordinal;
        j = i;
        j++;
        setIconImage(Toolkit.getDefaultToolkit().getImage(GetBrosNumber.class.getResource("/com/theanasuddin/bros/images/icon.png")));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        lblInputField1 = new javax.swing.JLabel();
        lblInputField2 = new javax.swing.JLabel();
        txtInputField1 = new javax.swing.JTextField();
        txtInputField1Disabled = new javax.swing.JTextField();
        txtInputField2 = new javax.swing.JTextField();
        txtInputField2Disabled = new javax.swing.JTextField();
        lblWelcome = new javax.swing.JLabel();
        lblNext = new javax.swing.JLabel();
        lblInputField3 = new javax.swing.JLabel();
        txtInputField3 = new javax.swing.JTextField();
        txtInputField3Disabled = new javax.swing.JTextField();
        lblInputField4 = new javax.swing.JLabel();
        txtInputField4 = new javax.swing.JTextField();
        txtInputField4Disabled = new javax.swing.JTextField();
        lblBackGroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Bros");
        setResizable(false);

        pnlMain.setPreferredSize(new java.awt.Dimension(528, 528));
        pnlMain.setLayout(null);

        lblInputField1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblInputField1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/input_field_1.png")));
        lblInputField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pnlMain.add(lblInputField1);
        lblInputField1.setBounds(60, 208, 410, 52);

        lblInputField2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblInputField2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/input_field_1.png")));
        lblInputField2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pnlMain.add(lblInputField2);
        lblInputField2.setBounds(60, 268, 410, 52);

        txtInputField1.setBackground(new Color(0,0,0,0));
        txtInputField1.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txtInputField1.setForeground(new java.awt.Color(235,234,237));
        txtInputField1.setBorder(null);
        txtInputField1.setSelectedTextColor(new Color(255,255,255));
        txtInputField1.setSelectionColor(new Color(48,213,25));
        txtInputField1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtInputField1CaretUpdate(evt);
            }
        });
        txtInputField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtInputField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtInputField1FocusLost(evt);
            }
        });
        txtInputField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtInputField1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtInputField1KeyTyped(evt);
            }
        });
        pnlMain.add(txtInputField1);
        txtInputField1.setBounds(70, 208, 390, 52);

        txtInputField1Disabled.setBackground(new Color(0,0,0,0));
        txtInputField1Disabled.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txtInputField1Disabled.setText("Enter home rent of " + serial + " member");
        txtInputField1Disabled.setBorder(null);
        txtInputField1Disabled.setDisabledTextColor(new Color(149,150,156));
        txtInputField1Disabled.setEnabled(false);
        pnlMain.add(txtInputField1Disabled);
        txtInputField1Disabled.setBounds(70, 208, 390, 52);

        txtInputField2.setBackground(new Color(0,0,0,0));
        txtInputField2.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txtInputField2.setForeground(new java.awt.Color(235,234,237));
        txtInputField2.setBorder(null);
        txtInputField2.setPreferredSize(new java.awt.Dimension(144, 18));
        txtInputField2.setSelectedTextColor(new Color(255,255,255));
        txtInputField2.setSelectionColor(new Color(48,213,25));
        txtInputField2.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtInputField2CaretUpdate(evt);
            }
        });
        txtInputField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtInputField2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtInputField2FocusLost(evt);
            }
        });
        txtInputField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtInputField2KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtInputField2KeyTyped(evt);
            }
        });
        pnlMain.add(txtInputField2);
        txtInputField2.setBounds(70, 268, 390, 52);

        txtInputField2Disabled.setBackground(new Color(0,0,0,0));
        txtInputField2Disabled.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txtInputField2Disabled.setText("Enter bazaar deposit of " + serial + " member");
        txtInputField2Disabled.setBorder(null);
        txtInputField2Disabled.setDisabledTextColor(new Color(149,150,156));
        txtInputField2Disabled.setEnabled(false);
        txtInputField2Disabled.setPreferredSize(new java.awt.Dimension(144, 18));
        pnlMain.add(txtInputField2Disabled);
        txtInputField2Disabled.setBounds(70, 268, 390, 52);

        lblWelcome.setFont(poppinsSemiBold);
        lblWelcome.setForeground(new java.awt.Color(255, 255, 255));
        if("".equals(com.theanasuddin.bros.classes.GetBrosNumber.name)){
            lblWelcome.setText("Hello!");
        }
        else{
            com.theanasuddin.bros.classes.GetBrosNumber.name = com.theanasuddin.bros.classes.GetBrosNumber.name.substring(0, 1).toUpperCase() + com.theanasuddin.bros.classes.GetBrosNumber.name.substring(1).toLowerCase();
            lblWelcome.setText("Hello, " + com.theanasuddin.bros.classes.GetBrosNumber.name + "!");
        }
        pnlMain.add(lblWelcome);
        lblWelcome.setBounds(60, 124, 410, 16);

        lblNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/next_button.png")));
        lblNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNextMouseClicked(evt);
            }
        });
        pnlMain.add(lblNext);
        lblNext.setBounds(378, 388, 92, 34);

        lblInputField3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblInputField3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/input_field_1.png")));
        lblInputField3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pnlMain.add(lblInputField3);
        lblInputField3.setBounds(60, 148, 410, 52);

        txtInputField3.setBackground(new Color(0,0,0,0));
        txtInputField3.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txtInputField3.setForeground(new java.awt.Color(235,234,237));
        txtInputField3.setBorder(null);
        txtInputField3.setSelectedTextColor(new Color(255,255,255));
        txtInputField3.setSelectionColor(new Color(48,213,25));
        txtInputField3.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtInputField3CaretUpdate(evt);
            }
        });
        txtInputField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtInputField3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtInputField3FocusLost(evt);
            }
        });
        txtInputField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtInputField3KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtInputField3KeyTyped(evt);
            }
        });
        pnlMain.add(txtInputField3);
        txtInputField3.setBounds(70, 148, 390, 52);

        txtInputField3Disabled.setBackground(new Color(0,0,0,0));
        txtInputField3Disabled.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txtInputField3Disabled.setText("Enter name of " + serial + " member");
        txtInputField3Disabled.setBorder(null);
        txtInputField3Disabled.setDisabledTextColor(new Color(149,150,156));
        txtInputField3Disabled.setEnabled(false);
        txtInputField3Disabled.setPreferredSize(new java.awt.Dimension(144, 18));
        pnlMain.add(txtInputField3Disabled);
        txtInputField3Disabled.setBounds(70, 148, 390, 52);

        lblInputField4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblInputField4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/input_field_1.png")));
        lblInputField4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pnlMain.add(lblInputField4);
        lblInputField4.setBounds(60, 328, 410, 52);

        txtInputField4.setBackground(new Color(0,0,0,0));
        txtInputField4.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txtInputField4.setForeground(new java.awt.Color(235,234,237));
        txtInputField4.setBorder(null);
        txtInputField4.setSelectedTextColor(new Color(255,255,255));
        txtInputField4.setSelectionColor(new Color(48,213,25));
        txtInputField4.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtInputField4CaretUpdate(evt);
            }
        });
        txtInputField4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtInputField4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtInputField4FocusLost(evt);
            }
        });
        txtInputField4.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtInputField4PropertyChange(evt);
            }
        });
        txtInputField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtInputField4KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtInputField4KeyTyped(evt);
            }
        });
        pnlMain.add(txtInputField4);
        txtInputField4.setBounds(70, 328, 390, 52);

        txtInputField4Disabled.setBackground(new Color(0,0,0,0));
        txtInputField4Disabled.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txtInputField4Disabled.setText("Enter total meal of " + serial + " member");
        txtInputField4Disabled.setBorder(null);
        txtInputField4Disabled.setDisabledTextColor(new Color(149,150,156));
        txtInputField4Disabled.setEnabled(false);
        txtInputField4Disabled.setPreferredSize(new java.awt.Dimension(144, 18));
        pnlMain.add(txtInputField4Disabled);
        txtInputField4Disabled.setBounds(70, 328, 390, 52);

        lblBackGroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/cherries.png")));
        lblBackGroundImage.setPreferredSize(new java.awt.Dimension(528, 528));
        pnlMain.add(lblBackGroundImage);
        lblBackGroundImage.setBounds(0, 0, 528, 528);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtInputField1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtInputField1CaretUpdate
        // TODO add your handling code here:
        if (txtInputField1.getText().length() != 0) {
            txtInputField1Disabled.setVisible(false);

            if (isLong(txtInputField1.getText().trim().replaceAll(" +", "")) || isDouble(txtInputField1.getText().trim().replaceAll(" +", ""))) {
                try {
                    if (Long.parseLong(txtInputField1.getText().trim().replaceAll(" +", "")) >= 0) {
                        individualHomeRentField = Double.parseDouble(txtInputField1.getText().trim().replaceAll(" +", ""));
                        lblNextEnabled1 = true;
                    }
                    if (Long.parseLong(txtInputField1.getText().trim().replaceAll(" +", "")) < 0) {
                        lblNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/next_button.png")));
                        lblNext.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                        lblNextEnabled = false;
                        lblNextEnabled1 = false;

                    }

                } catch (Exception e) {
                    if (Double.parseDouble(txtInputField1.getText().trim().replaceAll(" +", "")) >= 0) {
                        individualHomeRentField = Double.parseDouble(txtInputField1.getText().trim().replaceAll(" +", ""));
                        lblNextEnabled1 = true;
                    }
                    if (Double.parseDouble(txtInputField1.getText().trim().replaceAll(" +", "")) < 0) {
                        lblNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/next_button.png")));
                        lblNext.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                        lblNextEnabled = false;
                        lblNextEnabled1 = false;

                    }
                }

            } else {
                lblNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/next_button.png")));
                lblNext.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                lblNextEnabled = false;
                lblNextEnabled1 = false;

            }

        } else {
            txtInputField1Disabled.setVisible(true);
        }

        if (txtInputField1.getText().length() == 0 || txtInputField2.getText().length() == 0 || txtInputField3.getText().length() == 0 || txtInputField4.getText().length() == 0) {
            lblNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/next_button.png")));
            lblNext.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            lblNextEnabled = false;
            lblNextEnabled1 = false;
        }
        if (lblNextEnabled1 && lblNextEnabled2 && lblNextEnabled3 && lblNextEnabled4) {
            lblNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/next_button_activated.png")));
            lblNext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            lblNextEnabled = true;
        }

    }//GEN-LAST:event_txtInputField1CaretUpdate

    private void txtInputField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtInputField1FocusGained
        // TODO add your handling code here:
        if ("".equals(txtInputField1.getText())) {
            lblInputField1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/input_field_1_focused.png")));

        } else {
            lblInputField1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/input_field_1.1_focused_type.png")));
        }
    }//GEN-LAST:event_txtInputField1FocusGained

    private void txtInputField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtInputField1FocusLost
        // TODO add your handling code here:
        lblInputField1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/input_field_1.png")));
    }//GEN-LAST:event_txtInputField1FocusLost

    private void txtInputField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtInputField2FocusGained
        // TODO add your handling code here:
        if ("".equals(txtInputField2.getText())) {
            lblInputField2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/input_field_1_focused.png")));

        } else {
            lblInputField2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/input_field_2_focused_type.png")));
        }
    }//GEN-LAST:event_txtInputField2FocusGained

    private void txtInputField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtInputField2FocusLost
        // TODO add your handling code here:
        lblInputField2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/input_field_1.png")));
    }//GEN-LAST:event_txtInputField2FocusLost

    private void txtInputField3CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtInputField3CaretUpdate
        // TODO add your handling code here:
        if ("".equals(txtInputField3.getText().trim())) {
            txtInputField1Disabled.setText("Enter home rent of " + serial + " member");
            txtInputField2Disabled.setText("Enter bazaar deposit of " + serial + " member");
            txtInputField4Disabled.setText("Enter total meal of " + serial + " member");

        } else {
            txtInputField1Disabled.setText("Enter home rent of " + txtInputField3.getText().trim().replaceAll(" +", " "));
            txtInputField2Disabled.setText("Enter bazaar deposit of " + txtInputField3.getText().trim().replaceAll(" +", " "));
            txtInputField4Disabled.setText("Enter total meal of " + txtInputField3.getText().trim().replaceAll(" +", " "));

        }

        if (txtInputField3.getText().length() != 0) {
            txtInputField3Disabled.setVisible(false);
            try {
                if (validateString(txtInputField3.getText().trim().replaceAll(" +", "")) == true) {
                    membersNameField = txtInputField3.getText().trim().replaceAll(" +", " ");
                    if (membersNameField.contains(" ")) {
                        membersNameField = membersNameField.substring(0, membersNameField.indexOf(" "));
                    }
                    membersNameField = membersNameField.substring(0, 1).toUpperCase() + membersNameField.substring(1).toLowerCase();
                    lblNextEnabled3 = true;

                } else if (validateString(txtInputField3.getText().trim().replaceAll(" +", "")) == false) {
                    lblNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/next_button.png")));
                    lblNext.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                    lblNextEnabled = false;
                    lblNextEnabled3 = false;

                }
            } catch (Exception e) {

            }
        } else {
            txtInputField3Disabled.setVisible(true);
        }

        if (txtInputField1.getText().length() == 0 || txtInputField2.getText().length() == 0 || txtInputField3.getText().length() == 0 || txtInputField4.getText().length() == 0) {
            lblNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/next_button.png")));
            lblNext.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            lblNextEnabled = false;
            lblNextEnabled3 = false;
        }
        if (lblNextEnabled1 && lblNextEnabled2 && lblNextEnabled3 && lblNextEnabled4) {
            lblNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/next_button_activated.png")));
            lblNext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            lblNextEnabled = true;
        }


    }//GEN-LAST:event_txtInputField3CaretUpdate

    private void txtInputField3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtInputField3FocusGained
        // TODO add your handling code here:
        if ("".equals(txtInputField3.getText())) {
            lblInputField3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/input_field_1_focused.png")));

        } else {
            lblInputField3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/input_field_3_focused_type.png")));
        }


    }//GEN-LAST:event_txtInputField3FocusGained

    private void txtInputField3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtInputField3FocusLost
        // TODO add your handling code here:
        lblInputField3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/input_field_1.png")));
    }//GEN-LAST:event_txtInputField3FocusLost

    private void txtInputField4CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtInputField4CaretUpdate
        // TODO add your handling code here:
        if (txtInputField4.getText().length() != 0) {
            txtInputField4Disabled.setVisible(false);

            if (isLong(txtInputField4.getText().trim().replaceAll(" +", "")) || isDouble(txtInputField4.getText().trim().replaceAll(" +", ""))) {
                try {
                    if (Long.parseLong(txtInputField4.getText().trim().replaceAll(" +", "")) >= 0) {
                        individualMealField = Double.parseDouble(txtInputField4.getText().trim().replaceAll(" +", ""));
                        lblNextEnabled4 = true;
                    }
                    if (Long.parseLong(txtInputField4.getText().trim().replaceAll(" +", "")) < 0) {
                        lblNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/next_button.png")));
                        lblNext.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                        lblNextEnabled = false;
                        lblNextEnabled4 = false;

                    }

                } catch (Exception e) {
                    if (Double.parseDouble(txtInputField4.getText().trim().replaceAll(" +", "")) >= 0) {
                        individualMealField = Double.parseDouble(txtInputField4.getText().trim().replaceAll(" +", ""));
                        lblNextEnabled4 = true;
                    }
                    if (Double.parseDouble(txtInputField4.getText().trim().replaceAll(" +", "")) < 0) {
                        lblNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/next_button.png")));
                        lblNext.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                        lblNextEnabled = false;
                        lblNextEnabled4 = false;

                    }
                }

            } else {
                lblNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/next_button.png")));
                lblNext.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                lblNextEnabled = false;
                lblNextEnabled4 = false;

            }

        } else {
            txtInputField4Disabled.setVisible(true);
        }

        if (txtInputField1.getText().length() == 0 || txtInputField2.getText().length() == 0 || txtInputField3.getText().length() == 0 || txtInputField4.getText().length() == 0) {
            lblNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/next_button.png")));
            lblNext.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            lblNextEnabled = false;
            lblNextEnabled4 = false;
        }
        if (lblNextEnabled1 && lblNextEnabled2 && lblNextEnabled3 && lblNextEnabled4) {
            lblNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/next_button_activated.png")));
            lblNext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            lblNextEnabled = true;
        }


    }//GEN-LAST:event_txtInputField4CaretUpdate

    private void txtInputField4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtInputField4FocusGained
        // TODO add your handling code here:
        if ("".equals(txtInputField4.getText())) {
            lblInputField4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/input_field_1_focused.png")));

        } else {
            lblInputField4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/input_field_4_focused_type.png")));
        }
    }//GEN-LAST:event_txtInputField4FocusGained

    private void txtInputField4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtInputField4FocusLost
        // TODO add your handling code here:
        lblInputField4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/input_field_1.png")));
    }//GEN-LAST:event_txtInputField4FocusLost

    private void txtInputField4PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtInputField4PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInputField4PropertyChange

    private void txtInputField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInputField4KeyTyped
        // TODO add your handling code here:
        if ((evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') || (evt.getKeyChar() == '.')) {
            lblInputField4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/input_field_4_focused_type.png")));
        }
    }//GEN-LAST:event_txtInputField4KeyTyped

    private void txtInputField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInputField3KeyTyped
        // TODO add your handling code here:
        if (Character.isLetter(evt.getKeyChar())) {
            lblInputField3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/input_field_3_focused_type.png")));
        }

    }//GEN-LAST:event_txtInputField3KeyTyped

    private void txtInputField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInputField2KeyTyped
        // TODO add your handling code here:
        if ((evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') || (evt.getKeyChar() == '.')) {
            lblInputField2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/input_field_2_focused_type.png")));
        }
    }//GEN-LAST:event_txtInputField2KeyTyped

    private void txtInputField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInputField1KeyTyped
        // TODO add your handling code here:
        if ((evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') || (evt.getKeyChar() == '.')) {

            lblInputField1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/input_field_1.1_focused_type.png")));
        }
    }//GEN-LAST:event_txtInputField1KeyTyped

    private void txtInputField2CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtInputField2CaretUpdate
        // TODO add your handling code here:
        if (txtInputField2.getText().length() != 0) {
            txtInputField2Disabled.setVisible(false);

            if (isLong(txtInputField2.getText().trim().replaceAll(" +", "")) || isDouble(txtInputField2.getText().trim().replaceAll(" +", ""))) {
                try {
                    if (Long.parseLong(txtInputField2.getText().trim().replaceAll(" +", "")) >= 0) {
                        individualBazaarField = Double.parseDouble(txtInputField2.getText().trim().replaceAll(" +", ""));
                        lblNextEnabled2 = true;
                    }
                    if (Long.parseLong(txtInputField2.getText().trim().replaceAll(" +", "")) < 0) {
                        lblNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/next_button.png")));
                        lblNext.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                        lblNextEnabled = false;
                        lblNextEnabled2 = false;

                    }

                } catch (Exception e) {
                    if (Double.parseDouble(txtInputField2.getText().trim().replaceAll(" +", "")) >= 0) {
                        individualBazaarField = Double.parseDouble(txtInputField2.getText().trim().replaceAll(" +", ""));
                        lblNextEnabled2 = true;
                    }
                    if (Double.parseDouble(txtInputField2.getText().trim().replaceAll(" +", "")) < 0) {
                        lblNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/next_button.png")));
                        lblNext.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                        lblNextEnabled = false;
                        lblNextEnabled2 = false;

                    }
                }

            } else {
                lblNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/next_button.png")));
                lblNext.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                lblNextEnabled = false;
                lblNextEnabled2 = false;

            }

        } else {
            txtInputField2Disabled.setVisible(true);
        }

        if (txtInputField1.getText().length() == 0 || txtInputField2.getText().length() == 0 || txtInputField3.getText().length() == 0 || txtInputField4.getText().length() == 0) {
            lblNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/next_button.png")));
            lblNext.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            lblNextEnabled = false;
            lblNextEnabled2 = false;
        }
        if (lblNextEnabled1 && lblNextEnabled2 && lblNextEnabled3 && lblNextEnabled4) {
            lblNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/next_button_activated.png")));
            lblNext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            lblNextEnabled = true;
        }


    }//GEN-LAST:event_txtInputField2CaretUpdate

    private void lblNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNextMouseClicked
        // TODO add your handling code here:
        if (lblNextEnabled) {
            if (j <= GetBrosNumber.numberOfMembers) {

                if (j % 100 >= 11 && j % 100 <= 20) {
                    ordinal = j + "th";
                } else if (j % 10 == 1) {
                    ordinal = j + "st";
                } else if (j % 10 == 2) {
                    ordinal = j + "nd";
                } else if (j % 10 == 3) {
                    ordinal = j + "rd";
                } else {
                    ordinal = j + "th";
                }
                GetBrosDetails restBros = new GetBrosDetails(ordinal, j);
                restBros.setVisible(true);
                GetBrosDetails.membersName.add(GetBrosDetails.membersNameField);
                GetBrosDetails.individualHomeRent.add(GetBrosDetails.individualHomeRentField);
                GetBrosDetails.individualBazaar.add(GetBrosDetails.individualBazaarField);
                GetBrosDetails.individualMeal.add(GetBrosDetails.individualMealField);
                lblWelcome.setText("Continue..");
                lblNextEnabled = false;
                this.dispose();
            } else {
                GetBrosDetails.membersName.add(GetBrosDetails.membersNameField);
                GetBrosDetails.individualHomeRent.add(GetBrosDetails.individualHomeRentField);
                GetBrosDetails.individualBazaar.add(GetBrosDetails.individualBazaarField);
                GetBrosDetails.individualMeal.add(GetBrosDetails.individualMealField);
                this.dispose();
                new GetOtherBills().setVisible(true);
            }
        }
    }//GEN-LAST:event_lblNextMouseClicked

    private void txtInputField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInputField3KeyPressed
        // TODO add your handling code here:
        if (Character.isLetter(evt.getKeyChar()) || Character.isISOControl(evt.getKeyChar()) || Character.isWhitespace(evt.getKeyChar())
                || (evt.getKeyCode() == KeyEvent.VK_CONTROL) || (evt.getKeyCode() == KeyEvent.VK_SHIFT) || (evt.getKeyCode() == KeyEvent.VK_CAPS_LOCK)
                || (evt.getKeyCode() == KeyEvent.VK_COMMAND) || (evt.getKeyCode() == KeyEvent.VK_WINDOWS) || (evt.getKeyCode() == KeyEvent.VK_ALT)
                || (evt.getKeyCode() == KeyEvent.VK_ALT_GRAPH) || (evt.getKeyCode() == KeyEvent.VK_NUM_LOCK) || (evt.getKeyCode() == KeyEvent.VK_HOME)
                || (evt.getKeyCode() == KeyEvent.VK_END) || (evt.getKeyCode() == KeyEvent.VK_LEFT) || (evt.getKeyCode() == KeyEvent.VK_RIGHT)) {
            txtInputField3.setEditable(true);

        } else {
            txtInputField3.setEditable(false);
            getToolkit().beep();
        }
    }//GEN-LAST:event_txtInputField3KeyPressed

    private void txtInputField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInputField1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' || Character.isISOControl(evt.getKeyChar())
                || (evt.getKeyCode() == KeyEvent.VK_CONTROL) || (evt.getKeyCode() == KeyEvent.VK_SHIFT) || (evt.getKeyCode() == KeyEvent.VK_CAPS_LOCK)
                || (evt.getKeyCode() == KeyEvent.VK_COMMAND) || (evt.getKeyCode() == KeyEvent.VK_WINDOWS) || (evt.getKeyCode() == KeyEvent.VK_ALT)
                || (evt.getKeyCode() == KeyEvent.VK_ALT_GRAPH) || (evt.getKeyCode() == KeyEvent.VK_NUM_LOCK) || (evt.getKeyCode() == KeyEvent.VK_HOME)
                || (evt.getKeyCode() == KeyEvent.VK_END) || (evt.getKeyCode() == KeyEvent.VK_LEFT) || (evt.getKeyCode() == KeyEvent.VK_RIGHT) || (evt.getKeyCode() == KeyEvent.VK_DECIMAL)) {
            txtInputField1.setEditable(true);
        } else {
            txtInputField1.setEditable(false);
            getToolkit().beep();

        }
    }//GEN-LAST:event_txtInputField1KeyPressed

    private void txtInputField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInputField2KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' || Character.isISOControl(evt.getKeyChar())
                || (evt.getKeyCode() == KeyEvent.VK_CONTROL) || (evt.getKeyCode() == KeyEvent.VK_SHIFT) || (evt.getKeyCode() == KeyEvent.VK_CAPS_LOCK)
                || (evt.getKeyCode() == KeyEvent.VK_COMMAND) || (evt.getKeyCode() == KeyEvent.VK_WINDOWS) || (evt.getKeyCode() == KeyEvent.VK_ALT)
                || (evt.getKeyCode() == KeyEvent.VK_ALT_GRAPH) || (evt.getKeyCode() == KeyEvent.VK_NUM_LOCK) || (evt.getKeyCode() == KeyEvent.VK_HOME)
                || (evt.getKeyCode() == KeyEvent.VK_END) || (evt.getKeyCode() == KeyEvent.VK_LEFT) || (evt.getKeyCode() == KeyEvent.VK_RIGHT) || (evt.getKeyCode() == KeyEvent.VK_DECIMAL)) {
            txtInputField2.setEditable(true);
        } else {
            txtInputField2.setEditable(false);
            getToolkit().beep();

        }
    }//GEN-LAST:event_txtInputField2KeyPressed

    private void txtInputField4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInputField4KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' || Character.isISOControl(evt.getKeyChar())
                || (evt.getKeyCode() == KeyEvent.VK_CONTROL) || (evt.getKeyCode() == KeyEvent.VK_SHIFT) || (evt.getKeyCode() == KeyEvent.VK_CAPS_LOCK)
                || (evt.getKeyCode() == KeyEvent.VK_COMMAND) || (evt.getKeyCode() == KeyEvent.VK_WINDOWS) || (evt.getKeyCode() == KeyEvent.VK_ALT)
                || (evt.getKeyCode() == KeyEvent.VK_ALT_GRAPH) || (evt.getKeyCode() == KeyEvent.VK_NUM_LOCK) || (evt.getKeyCode() == KeyEvent.VK_HOME)
                || (evt.getKeyCode() == KeyEvent.VK_END) || (evt.getKeyCode() == KeyEvent.VK_LEFT) || (evt.getKeyCode() == KeyEvent.VK_RIGHT) || (evt.getKeyCode() == KeyEvent.VK_DECIMAL)) {
            txtInputField4.setEditable(true);
        } else {
            txtInputField4.setEditable(false);
            getToolkit().beep();

        }
    }//GEN-LAST:event_txtInputField4KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GetBrosDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GetBrosDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GetBrosDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GetBrosDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GetBrosDetails().setVisible(true);
            }
        });
    }
    static String serial;
    static int j;
    static boolean lblNextEnabled = false;
    static boolean lblNextEnabled1 = false;
    static boolean lblNextEnabled2 = false;
    static boolean lblNextEnabled3 = false;
    static boolean lblNextEnabled4 = false;

    public boolean validateString(String str) {
        str = str.toLowerCase();
        char[] charArray = str.toCharArray();
        for (int i = 0; i < charArray.length; i++) {
            char ch = charArray[i];
            if (!(ch >= 'a' && ch <= 'z')) {
                return false;
            }
        }
        return true;
    }

    public boolean isLong(String str) {
        try {
            Long.parseLong(str);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }

    public boolean isDouble(String str) {
        try {
            Double.parseDouble(str);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }

    static ArrayList<String> membersName = new ArrayList<String>();
    static ArrayList<Double> individualHomeRent = new ArrayList<Double>();
    static ArrayList<Double> individualMeal = new ArrayList<Double>();
    static ArrayList<Double> individualBazaar = new ArrayList<Double>();
    static double individualHomeRentField;
    static double individualMealField;
    static double individualBazaarField;
    static String membersNameField;


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBackGroundImage;
    private javax.swing.JLabel lblInputField1;
    private javax.swing.JLabel lblInputField2;
    private javax.swing.JLabel lblInputField3;
    private javax.swing.JLabel lblInputField4;
    private javax.swing.JLabel lblNext;
    private static javax.swing.JLabel lblWelcome;
    private javax.swing.JPanel pnlMain;
    public javax.swing.JTextField txtInputField1;
    private javax.swing.JTextField txtInputField1Disabled;
    private javax.swing.JTextField txtInputField2;
    private javax.swing.JTextField txtInputField2Disabled;
    public javax.swing.JTextField txtInputField3;
    private javax.swing.JTextField txtInputField3Disabled;
    private javax.swing.JTextField txtInputField4;
    private javax.swing.JTextField txtInputField4Disabled;
    // End of variables declaration//GEN-END:variables
}
