/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.theanasuddin.bros.classes;

import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.GraphicsEnvironment;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.util.Collections;
import javax.swing.JOptionPane;

/**
 *
 * @author Anas
 */
public class GetOtherBills extends javax.swing.JFrame {

    /**
     * Creates new form GetOtherBills
     */
    Font poppinsSemiBold = null;
    Font poppinsExtraLight = null;
    Font poppinsThin = null;

    public GetOtherBills() {
        try {
            poppinsSemiBold = Font.createFont(Font.TRUETYPE_FONT, new File("src/com/theanasuddin/bros/fonts/PoppinsSemiBold.ttf")).deriveFont(20f);
            poppinsExtraLight = Font.createFont(Font.TRUETYPE_FONT, new File("src/com/theanasuddin/bros/fonts/PoppinsSemiBold.ttf")).deriveFont(15f);
            poppinsThin = Font.createFont(Font.TRUETYPE_FONT, new File("src/com/theanasuddin/bros/fonts/PoppinsThin.ttf")).deriveFont(15f);
            GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
            ge.registerFont(poppinsSemiBold);
            ge.registerFont(poppinsExtraLight);
            ge.registerFont(poppinsThin);
        } catch (FontFormatException | IOException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        setIconImage(Toolkit.getDefaultToolkit().getImage(GetOtherBills.class.getResource("/com/theanasuddin/bros/images/icon.png")));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        lblInputField1 = new javax.swing.JLabel();
        lblInputField2 = new javax.swing.JLabel();
        txtInputField1 = new javax.swing.JTextField();
        txtInputField1Disabled = new javax.swing.JTextField();
        txtInputField2 = new javax.swing.JTextField();
        txtInputField2Disabled = new javax.swing.JTextField();
        lblInputField3 = new javax.swing.JLabel();
        txtInputField3 = new javax.swing.JTextField();
        txtInputField3Disabled = new javax.swing.JTextField();
        lblInputField4 = new javax.swing.JLabel();
        txtInputField4 = new javax.swing.JTextField();
        txtInputField4Disabled = new javax.swing.JTextField();
        lblInputField5 = new javax.swing.JLabel();
        txtInputField5 = new javax.swing.JTextField();
        txtInputField5Disabled = new javax.swing.JTextField();
        lblInputField6 = new javax.swing.JLabel();
        txtInputField6 = new javax.swing.JTextField();
        txtInputField6Disabled = new javax.swing.JTextField();
        lblInputField7 = new javax.swing.JLabel();
        txtInputField7 = new javax.swing.JTextField();
        txtInputField7Disabled = new javax.swing.JTextField();
        lblWelcome = new javax.swing.JLabel();
        lblNext = new javax.swing.JLabel();
        lblBackGroundImage = new javax.swing.JLabel();

        setTitle("Bros");
        setResizable(false);

        pnlMain.setPreferredSize(new java.awt.Dimension(528, 528));
        pnlMain.setLayout(null);

        lblInputField1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblInputField1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/input_field_1.png")));
        lblInputField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pnlMain.add(lblInputField1);
        lblInputField1.setBounds(60, 58, 410, 52);

        lblInputField2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblInputField2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/input_field_1.png")));
        lblInputField2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pnlMain.add(lblInputField2);
        lblInputField2.setBounds(60, 238, 410, 52);

        txtInputField1.setBackground(new Color(0,0,0,0));
        txtInputField1.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txtInputField1.setForeground(new java.awt.Color(235,234,237));
        txtInputField1.setBorder(null);
        txtInputField1.setSelectedTextColor(new Color(255,255,255));
        txtInputField1.setSelectionColor(new Color(48,213,25));
        txtInputField1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtInputField1CaretUpdate(evt);
            }
        });
        txtInputField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtInputField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtInputField1FocusLost(evt);
            }
        });
        txtInputField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtInputField1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtInputField1KeyTyped(evt);
            }
        });
        pnlMain.add(txtInputField1);
        txtInputField1.setBounds(70, 58, 390, 52);

        txtInputField1Disabled.setBackground(new Color(0,0,0,0));
        txtInputField1Disabled.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txtInputField1Disabled.setText("Enter electricity bill");
        txtInputField1Disabled.setBorder(null);
        txtInputField1Disabled.setDisabledTextColor(new Color(149,150,156));
        txtInputField1Disabled.setEnabled(false);
        pnlMain.add(txtInputField1Disabled);
        txtInputField1Disabled.setBounds(70, 58, 390, 52);

        txtInputField2.setBackground(new Color(0,0,0,0));
        txtInputField2.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txtInputField2.setForeground(new java.awt.Color(235,234,237));
        txtInputField2.setBorder(null);
        txtInputField2.setPreferredSize(new java.awt.Dimension(144, 18));
        txtInputField2.setSelectedTextColor(new Color(255,255,255));
        txtInputField2.setSelectionColor(new Color(48,213,25));
        txtInputField2.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtInputField2CaretUpdate(evt);
            }
        });
        txtInputField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtInputField2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtInputField2FocusLost(evt);
            }
        });
        txtInputField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtInputField2KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtInputField2KeyTyped(evt);
            }
        });
        pnlMain.add(txtInputField2);
        txtInputField2.setBounds(70, 238, 390, 52);

        txtInputField2Disabled.setBackground(new Color(0,0,0,0));
        txtInputField2Disabled.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txtInputField2Disabled.setText("Enter water bill");
        txtInputField2Disabled.setBorder(null);
        txtInputField2Disabled.setDisabledTextColor(new Color(149,150,156));
        txtInputField2Disabled.setEnabled(false);
        txtInputField2Disabled.setPreferredSize(new java.awt.Dimension(144, 18));
        pnlMain.add(txtInputField2Disabled);
        txtInputField2Disabled.setBounds(70, 238, 390, 52);

        lblInputField3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblInputField3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/input_field_1.png")));
        lblInputField3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pnlMain.add(lblInputField3);
        lblInputField3.setBounds(60, 118, 410, 52);

        txtInputField3.setBackground(new Color(0,0,0,0));
        txtInputField3.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txtInputField3.setForeground(new java.awt.Color(235,234,237));
        txtInputField3.setBorder(null);
        txtInputField3.setSelectedTextColor(new Color(255,255,255));
        txtInputField3.setSelectionColor(new Color(48,213,25));
        txtInputField3.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtInputField3CaretUpdate(evt);
            }
        });
        txtInputField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtInputField3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtInputField3FocusLost(evt);
            }
        });
        txtInputField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtInputField3KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtInputField3KeyTyped(evt);
            }
        });
        pnlMain.add(txtInputField3);
        txtInputField3.setBounds(70, 118, 390, 52);

        txtInputField3Disabled.setBackground(new Color(0,0,0,0));
        txtInputField3Disabled.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txtInputField3Disabled.setText("Enter internet bill");
        txtInputField3Disabled.setBorder(null);
        txtInputField3Disabled.setDisabledTextColor(new Color(149,150,156));
        txtInputField3Disabled.setEnabled(false);
        pnlMain.add(txtInputField3Disabled);
        txtInputField3Disabled.setBounds(70, 118, 390, 52);

        lblInputField4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblInputField4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/input_field_1.png")));
        lblInputField4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pnlMain.add(lblInputField4);
        lblInputField4.setBounds(60, 178, 410, 52);

        txtInputField4.setBackground(new Color(0,0,0,0));
        txtInputField4.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txtInputField4.setForeground(new java.awt.Color(235,234,237));
        txtInputField4.setBorder(null);
        txtInputField4.setSelectedTextColor(new Color(255,255,255));
        txtInputField4.setSelectionColor(new Color(48,213,25));
        txtInputField4.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtInputField4CaretUpdate(evt);
            }
        });
        txtInputField4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtInputField4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtInputField4FocusLost(evt);
            }
        });
        txtInputField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtInputField4KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtInputField4KeyTyped(evt);
            }
        });
        pnlMain.add(txtInputField4);
        txtInputField4.setBounds(70, 178, 390, 52);

        txtInputField4Disabled.setBackground(new Color(0,0,0,0));
        txtInputField4Disabled.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txtInputField4Disabled.setText("Enter gas bill");
        txtInputField4Disabled.setBorder(null);
        txtInputField4Disabled.setDisabledTextColor(new Color(149,150,156));
        txtInputField4Disabled.setEnabled(false);
        pnlMain.add(txtInputField4Disabled);
        txtInputField4Disabled.setBounds(70, 178, 390, 52);

        lblInputField5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblInputField5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/input_field_1.png")));
        lblInputField5.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pnlMain.add(lblInputField5);
        lblInputField5.setBounds(60, 298, 410, 52);

        txtInputField5.setBackground(new Color(0,0,0,0));
        txtInputField5.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txtInputField5.setForeground(new java.awt.Color(235,234,237));
        txtInputField5.setBorder(null);
        txtInputField5.setSelectedTextColor(new Color(255,255,255));
        txtInputField5.setSelectionColor(new Color(48,213,25));
        txtInputField5.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtInputField5CaretUpdate(evt);
            }
        });
        txtInputField5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtInputField5FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtInputField5FocusLost(evt);
            }
        });
        txtInputField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtInputField5KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtInputField5KeyTyped(evt);
            }
        });
        pnlMain.add(txtInputField5);
        txtInputField5.setBounds(70, 298, 390, 52);

        txtInputField5Disabled.setBackground(new Color(0,0,0,0));
        txtInputField5Disabled.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txtInputField5Disabled.setText("Enter housemaid's bill");
        txtInputField5Disabled.setBorder(null);
        txtInputField5Disabled.setDisabledTextColor(new Color(149,150,156));
        txtInputField5Disabled.setEnabled(false);
        pnlMain.add(txtInputField5Disabled);
        txtInputField5Disabled.setBounds(70, 298, 390, 52);

        lblInputField6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblInputField6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/input_field_1.png")));
        lblInputField6.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pnlMain.add(lblInputField6);
        lblInputField6.setBounds(60, 358, 410, 52);

        txtInputField6.setBackground(new Color(0,0,0,0));
        txtInputField6.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txtInputField6.setForeground(new java.awt.Color(235,234,237));
        txtInputField6.setBorder(null);
        txtInputField6.setSelectedTextColor(new Color(255,255,255));
        txtInputField6.setSelectionColor(new Color(48,213,25));
        txtInputField6.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtInputField6CaretUpdate(evt);
            }
        });
        txtInputField6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtInputField6FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtInputField6FocusLost(evt);
            }
        });
        txtInputField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtInputField6KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtInputField6KeyTyped(evt);
            }
        });
        pnlMain.add(txtInputField6);
        txtInputField6.setBounds(70, 358, 390, 52);

        txtInputField6Disabled.setBackground(new Color(0,0,0,0));
        txtInputField6Disabled.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txtInputField6Disabled.setText("Enter stairway cleaning bill");
        txtInputField6Disabled.setBorder(null);
        txtInputField6Disabled.setDisabledTextColor(new Color(149,150,156));
        txtInputField6Disabled.setEnabled(false);
        pnlMain.add(txtInputField6Disabled);
        txtInputField6Disabled.setBounds(70, 358, 390, 52);

        lblInputField7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblInputField7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/input_field_1.png")));
        lblInputField7.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pnlMain.add(lblInputField7);
        lblInputField7.setBounds(60, 418, 410, 52);

        txtInputField7.setBackground(new Color(0,0,0,0));
        txtInputField7.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txtInputField7.setForeground(new java.awt.Color(235,234,237));
        txtInputField7.setBorder(null);
        txtInputField7.setSelectedTextColor(new Color(255,255,255));
        txtInputField7.setSelectionColor(new Color(48,213,25));
        txtInputField7.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtInputField7CaretUpdate(evt);
            }
        });
        txtInputField7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtInputField7FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtInputField7FocusLost(evt);
            }
        });
        txtInputField7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtInputField7KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtInputField7KeyTyped(evt);
            }
        });
        pnlMain.add(txtInputField7);
        txtInputField7.setBounds(70, 418, 390, 52);

        txtInputField7Disabled.setBackground(new Color(0,0,0,0));
        txtInputField7Disabled.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txtInputField7Disabled.setText("Enter welfare association's bill");
        txtInputField7Disabled.setBorder(null);
        txtInputField7Disabled.setDisabledTextColor(new Color(149,150,156));
        txtInputField7Disabled.setEnabled(false);
        pnlMain.add(txtInputField7Disabled);
        txtInputField7Disabled.setBounds(70, 418, 390, 52);

        lblWelcome.setFont(poppinsSemiBold);
        lblWelcome.setForeground(new java.awt.Color(255, 255, 255));
        lblWelcome.setText("Other Bills");
        pnlMain.add(lblWelcome);
        lblWelcome.setBounds(60, 34, 110, 16);

        lblNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/next_button.png")));
        lblNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNextMouseClicked(evt);
            }
        });
        pnlMain.add(lblNext);
        lblNext.setBounds(378, 478, 92, 34);

        lblBackGroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/cherries.png")));
        lblBackGroundImage.setPreferredSize(new java.awt.Dimension(528, 528));
        pnlMain.add(lblBackGroundImage);
        lblBackGroundImage.setBounds(0, 0, 528, 528);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtInputField1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtInputField1CaretUpdate
        // TODO add your handling code here:
        if (txtInputField1.getText().length() != 0) {
            txtInputField1Disabled.setVisible(false);

            if (isLong(txtInputField1.getText().trim().replaceAll(" +", "")) || isDouble(txtInputField1.getText().trim().replaceAll(" +", ""))) {
                try {
                    if (Long.parseLong(txtInputField1.getText().trim().replaceAll(" +", "")) >= 0) {
                        electricityBill = Long.parseLong(txtInputField1.getText().trim().replaceAll(" +", ""));
                        lblNextEnabled1 = true;
                    }
                    if (Long.parseLong(txtInputField1.getText().trim().replaceAll(" +", "")) < 0) {
                        lblNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/next_button.png")));
                        lblNext.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                        lblNextEnabled = false;
                        lblNextEnabled1 = false;

                    }

                } catch (Exception e) {
                    if (Double.parseDouble(txtInputField1.getText().trim().replaceAll(" +", "")) >= 0) {
                        electricityBill = Double.parseDouble(txtInputField1.getText().trim().replaceAll(" +", ""));
                        lblNextEnabled1 = true;
                    }
                    if (Double.parseDouble(txtInputField1.getText().trim().replaceAll(" +", "")) < 0) {
                        lblNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/next_button.png")));
                        lblNext.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                        lblNextEnabled = false;
                        lblNextEnabled1 = false;

                    }
                }

            } else {
                lblNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/next_button.png")));
                lblNext.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                lblNextEnabled = false;
                lblNextEnabled1 = false;

            }

        } else {
            txtInputField1Disabled.setVisible(true);
        }

        if (txtInputField1.getText().length() == 0 || txtInputField2.getText().length() == 0 || txtInputField3.getText().length() == 0 || txtInputField4.getText().length() == 0 || txtInputField5.getText().length() == 0 || txtInputField6.getText().length() == 0 || txtInputField7.getText().length() == 0) {
            lblNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/next_button.png")));
            lblNext.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            lblNextEnabled = false;
            lblNextEnabled1 = false;
        }
        if (lblNextEnabled1 && lblNextEnabled2 && lblNextEnabled3 && lblNextEnabled4 && lblNextEnabled5 && lblNextEnabled6 && lblNextEnabled7) {
            lblNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/next_button_activated.png")));
            lblNext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            lblNextEnabled = true;
        }
    }//GEN-LAST:event_txtInputField1CaretUpdate

    private void txtInputField2CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtInputField2CaretUpdate
        // TODO add your handling code here:
        if (txtInputField2.getText().length() != 0) {
            txtInputField2Disabled.setVisible(false);

            if (isLong(txtInputField2.getText().trim().replaceAll(" +", "")) || isDouble(txtInputField2.getText().trim().replaceAll(" +", ""))) {
                try {
                    if (Long.parseLong(txtInputField2.getText().trim().replaceAll(" +", "")) >= 0) {
                        waterBill = Long.parseLong(txtInputField2.getText().trim().replaceAll(" +", ""));
                        lblNextEnabled2 = true;
                    }
                    if (Long.parseLong(txtInputField2.getText().trim().replaceAll(" +", "")) < 0) {
                        lblNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/next_button.png")));
                        lblNext.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                        lblNextEnabled = false;
                        lblNextEnabled2 = false;

                    }

                } catch (Exception e) {
                    if (Double.parseDouble(txtInputField2.getText().trim().replaceAll(" +", "")) >= 0) {
                        waterBill = Double.parseDouble(txtInputField2.getText().trim().replaceAll(" +", ""));
                        lblNextEnabled2 = true;
                    }
                    if (Double.parseDouble(txtInputField2.getText().trim().replaceAll(" +", "")) < 0) {
                        lblNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/next_button.png")));
                        lblNext.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                        lblNextEnabled = false;
                        lblNextEnabled2 = false;

                    }
                }

            } else {
                lblNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/next_button.png")));
                lblNext.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                lblNextEnabled = false;
                lblNextEnabled2 = false;

            }

        } else {
            txtInputField2Disabled.setVisible(true);
        }

        if (txtInputField1.getText().length() == 0 || txtInputField2.getText().length() == 0 || txtInputField3.getText().length() == 0 || txtInputField4.getText().length() == 0 || txtInputField5.getText().length() == 0 || txtInputField6.getText().length() == 0 || txtInputField7.getText().length() == 0) {
            lblNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/next_button.png")));
            lblNext.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            lblNextEnabled = false;
            lblNextEnabled2 = false;
        }
        if (lblNextEnabled1 && lblNextEnabled2 && lblNextEnabled3 && lblNextEnabled4 && lblNextEnabled5 && lblNextEnabled6 && lblNextEnabled7) {
            lblNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/next_button_activated.png")));
            lblNext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            lblNextEnabled = true;
        }
    }//GEN-LAST:event_txtInputField2CaretUpdate

    private void txtInputField3CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtInputField3CaretUpdate
        // TODO add your handling code here:
        if (txtInputField3.getText().length() != 0) {
            txtInputField3Disabled.setVisible(false);

            if (isLong(txtInputField3.getText().trim().replaceAll(" +", "")) || isDouble(txtInputField3.getText().trim().replaceAll(" +", ""))) {
                try {
                    if (Long.parseLong(txtInputField3.getText().trim().replaceAll(" +", "")) >= 0) {
                        internetBill = Long.parseLong(txtInputField3.getText().trim().replaceAll(" +", ""));
                        lblNextEnabled3 = true;
                    }
                    if (Long.parseLong(txtInputField3.getText().trim().replaceAll(" +", "")) < 0) {
                        lblNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/next_button.png")));
                        lblNext.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                        lblNextEnabled = false;
                        lblNextEnabled3 = false;

                    }

                } catch (Exception e) {
                    if (Double.parseDouble(txtInputField3.getText().trim().replaceAll(" +", "")) >= 0) {
                        internetBill = Double.parseDouble(txtInputField3.getText().trim().replaceAll(" +", ""));
                        lblNextEnabled3 = true;
                    }
                    if (Double.parseDouble(txtInputField3.getText().trim().replaceAll(" +", "")) < 0) {
                        lblNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/next_button.png")));
                        lblNext.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                        lblNextEnabled = false;
                        lblNextEnabled3 = false;

                    }
                }

            } else {
                lblNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/next_button.png")));
                lblNext.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                lblNextEnabled = false;
                lblNextEnabled3 = false;

            }

        } else {
            txtInputField3Disabled.setVisible(true);
        }

        if (txtInputField1.getText().length() == 0 || txtInputField2.getText().length() == 0 || txtInputField3.getText().length() == 0 || txtInputField4.getText().length() == 0 || txtInputField5.getText().length() == 0 || txtInputField6.getText().length() == 0 || txtInputField7.getText().length() == 0) {
            lblNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/next_button.png")));
            lblNext.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            lblNextEnabled = false;
            lblNextEnabled3 = false;
        }
        if (lblNextEnabled1 && lblNextEnabled2 && lblNextEnabled3 && lblNextEnabled4 && lblNextEnabled5 && lblNextEnabled6 && lblNextEnabled7) {
            lblNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/next_button_activated.png")));
            lblNext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            lblNextEnabled = true;
        }
    }//GEN-LAST:event_txtInputField3CaretUpdate

    private void txtInputField4CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtInputField4CaretUpdate
        // TODO add your handling code here:
        if (txtInputField4.getText().length() != 0) {
            txtInputField4Disabled.setVisible(false);

            if (isLong(txtInputField4.getText().trim().replaceAll(" +", "")) || isDouble(txtInputField4.getText().trim().replaceAll(" +", ""))) {
                try {
                    if (Long.parseLong(txtInputField4.getText().trim().replaceAll(" +", "")) >= 0) {
                        gasBill = Long.parseLong(txtInputField4.getText().trim().replaceAll(" +", ""));
                        lblNextEnabled4 = true;
                    }
                    if (Long.parseLong(txtInputField4.getText().trim().replaceAll(" +", "")) < 0) {
                        lblNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/next_button.png")));
                        lblNext.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                        lblNextEnabled = false;
                        lblNextEnabled4 = false;

                    }

                } catch (Exception e) {
                    if (Double.parseDouble(txtInputField4.getText().trim().replaceAll(" +", "")) >= 0) {
                        gasBill = Double.parseDouble(txtInputField4.getText().trim().replaceAll(" +", ""));
                        lblNextEnabled4 = true;
                    }
                    if (Double.parseDouble(txtInputField4.getText().trim().replaceAll(" +", "")) < 0) {
                        lblNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/next_button.png")));
                        lblNext.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                        lblNextEnabled = false;
                        lblNextEnabled4 = false;

                    }
                }

            } else {
                lblNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/next_button.png")));
                lblNext.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                lblNextEnabled = false;
                lblNextEnabled4 = false;

            }

        } else {
            txtInputField4Disabled.setVisible(true);
        }

        if (txtInputField1.getText().length() == 0 || txtInputField2.getText().length() == 0 || txtInputField3.getText().length() == 0 || txtInputField4.getText().length() == 0 || txtInputField5.getText().length() == 0 || txtInputField6.getText().length() == 0 || txtInputField7.getText().length() == 0) {
            lblNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/next_button.png")));
            lblNext.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            lblNextEnabled = false;
            lblNextEnabled4 = false;
        }
        if (lblNextEnabled1 && lblNextEnabled2 && lblNextEnabled3 && lblNextEnabled4 && lblNextEnabled5 && lblNextEnabled6 && lblNextEnabled7) {
            lblNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/next_button_activated.png")));
            lblNext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            lblNextEnabled = true;
        }
    }//GEN-LAST:event_txtInputField4CaretUpdate

    private void txtInputField5CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtInputField5CaretUpdate
        // TODO add your handling code here:
        if (txtInputField5.getText().length() != 0) {
            txtInputField5Disabled.setVisible(false);

            if (isLong(txtInputField5.getText().trim().replaceAll(" +", "")) || isDouble(txtInputField5.getText().trim().replaceAll(" +", ""))) {
                try {
                    if (Long.parseLong(txtInputField5.getText().trim().replaceAll(" +", "")) >= 0) {
                        housemaidBill = Long.parseLong(txtInputField5.getText().trim().replaceAll(" +", ""));
                        lblNextEnabled5 = true;
                    }
                    if (Long.parseLong(txtInputField5.getText().trim().replaceAll(" +", "")) < 0) {
                        lblNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/next_button.png")));
                        lblNext.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                        lblNextEnabled = false;
                        lblNextEnabled5 = false;

                    }

                } catch (Exception e) {
                    if (Double.parseDouble(txtInputField5.getText().trim().replaceAll(" +", "")) >= 0) {
                        housemaidBill = Double.parseDouble(txtInputField5.getText().trim().replaceAll(" +", ""));
                        lblNextEnabled5 = true;
                    }
                    if (Double.parseDouble(txtInputField5.getText().trim().replaceAll(" +", "")) < 0) {
                        lblNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/next_button.png")));
                        lblNext.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                        lblNextEnabled = false;
                        lblNextEnabled5 = false;

                    }
                }

            } else {
                lblNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/next_button.png")));
                lblNext.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                lblNextEnabled = false;
                lblNextEnabled5 = false;

            }

        } else {
            txtInputField5Disabled.setVisible(true);
        }

        if (txtInputField1.getText().length() == 0 || txtInputField2.getText().length() == 0 || txtInputField3.getText().length() == 0 || txtInputField4.getText().length() == 0 || txtInputField5.getText().length() == 0 || txtInputField6.getText().length() == 0 || txtInputField7.getText().length() == 0) {
            lblNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/next_button.png")));
            lblNext.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            lblNextEnabled = false;
            lblNextEnabled5 = false;
        }
        if (lblNextEnabled1 && lblNextEnabled2 && lblNextEnabled3 && lblNextEnabled4 && lblNextEnabled5 && lblNextEnabled6 && lblNextEnabled7) {
            lblNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/next_button_activated.png")));
            lblNext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            lblNextEnabled = true;
        }
    }//GEN-LAST:event_txtInputField5CaretUpdate

    private void txtInputField6CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtInputField6CaretUpdate
        // TODO add your handling code here:
        if (txtInputField6.getText().length() != 0) {
            txtInputField6Disabled.setVisible(false);

            if (isLong(txtInputField6.getText().trim().replaceAll(" +", "")) || isDouble(txtInputField6.getText().trim().replaceAll(" +", ""))) {
                try {
                    if (Long.parseLong(txtInputField6.getText().trim().replaceAll(" +", "")) >= 0) {
                        stairCleaningBill = Long.parseLong(txtInputField6.getText().trim().replaceAll(" +", ""));
                        lblNextEnabled6 = true;
                    }
                    if (Long.parseLong(txtInputField6.getText().trim().replaceAll(" +", "")) < 0) {
                        lblNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/next_button.png")));
                        lblNext.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                        lblNextEnabled = false;
                        lblNextEnabled6 = false;

                    }

                } catch (Exception e) {
                    if (Double.parseDouble(txtInputField6.getText().trim().replaceAll(" +", "")) >= 0) {
                        stairCleaningBill = Double.parseDouble(txtInputField6.getText().trim().replaceAll(" +", ""));
                        lblNextEnabled6 = true;
                    }
                    if (Double.parseDouble(txtInputField6.getText().trim().replaceAll(" +", "")) < 0) {
                        lblNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/next_button.png")));
                        lblNext.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                        lblNextEnabled = false;
                        lblNextEnabled6 = false;

                    }
                }

            } else {
                lblNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/next_button.png")));
                lblNext.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                lblNextEnabled = false;
                lblNextEnabled6 = false;

            }

        } else {
            txtInputField6Disabled.setVisible(true);
        }

        if (txtInputField1.getText().length() == 0 || txtInputField2.getText().length() == 0 || txtInputField3.getText().length() == 0 || txtInputField4.getText().length() == 0 || txtInputField5.getText().length() == 0 || txtInputField6.getText().length() == 0 || txtInputField7.getText().length() == 0) {
            lblNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/next_button.png")));
            lblNext.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            lblNextEnabled = false;
            lblNextEnabled6 = false;
        }
        if (lblNextEnabled1 && lblNextEnabled2 && lblNextEnabled3 && lblNextEnabled4 && lblNextEnabled5 && lblNextEnabled6 && lblNextEnabled7) {
            lblNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/next_button_activated.png")));
            lblNext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            lblNextEnabled = true;
        }
    }//GEN-LAST:event_txtInputField6CaretUpdate

    private void txtInputField7CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtInputField7CaretUpdate
        // TODO add your handling code here:
        if (txtInputField7.getText().length() != 0) {
            txtInputField7Disabled.setVisible(false);

            if (isLong(txtInputField7.getText().trim().replaceAll(" +", "")) || isDouble(txtInputField7.getText().trim().replaceAll(" +", ""))) {
                try {
                    if (Long.parseLong(txtInputField7.getText().trim().replaceAll(" +", "")) >= 0) {
                        welfareAssociationBill = Long.parseLong(txtInputField7.getText().trim().replaceAll(" +", ""));
                        lblNextEnabled7 = true;
                    }
                    if (Long.parseLong(txtInputField7.getText().trim().replaceAll(" +", "")) < 0) {
                        lblNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/next_button.png")));
                        lblNext.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                        lblNextEnabled = false;
                        lblNextEnabled7 = false;

                    }

                } catch (Exception e) {
                    if (Double.parseDouble(txtInputField7.getText().trim().replaceAll(" +", "")) >= 0) {
                        welfareAssociationBill = Double.parseDouble(txtInputField7.getText().trim().replaceAll(" +", ""));
                        lblNextEnabled7 = true;
                    }
                    if (Double.parseDouble(txtInputField7.getText().trim().replaceAll(" +", "")) < 0) {
                        lblNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/next_button.png")));
                        lblNext.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                        lblNextEnabled = false;
                        lblNextEnabled7 = false;

                    }
                }

            } else {
                lblNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/next_button.png")));
                lblNext.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                lblNextEnabled = false;
                lblNextEnabled7 = false;

            }

        } else {
            txtInputField7Disabled.setVisible(true);
        }

        if (txtInputField1.getText().length() == 0 || txtInputField2.getText().length() == 0 || txtInputField3.getText().length() == 0 || txtInputField4.getText().length() == 0 || txtInputField5.getText().length() == 0 || txtInputField6.getText().length() == 0 || txtInputField7.getText().length() == 0) {
            lblNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/next_button.png")));
            lblNext.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            lblNextEnabled = false;
            lblNextEnabled7 = false;
        }
        if (lblNextEnabled1 && lblNextEnabled2 && lblNextEnabled3 && lblNextEnabled4 && lblNextEnabled5 && lblNextEnabled6 && lblNextEnabled7) {
            lblNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/next_button_activated.png")));
            lblNext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            lblNextEnabled = true;
        }
    }//GEN-LAST:event_txtInputField7CaretUpdate

    private void txtInputField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInputField1KeyTyped
        // TODO add your handling code here:
        if ((evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') || (evt.getKeyChar() == '.')) {
            lblInputField1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/input_field_electricity_focused_type.png")));
        }
    }//GEN-LAST:event_txtInputField1KeyTyped

    private void txtInputField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInputField2KeyTyped
        // TODO add your handling code here:
        if ((evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') || (evt.getKeyChar() == '.')) {
            lblInputField2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/input_field_water_focused_type.png")));
        }
    }//GEN-LAST:event_txtInputField2KeyTyped

    private void txtInputField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInputField3KeyTyped
        // TODO add your handling code here:
        if ((evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') || (evt.getKeyChar() == '.')) {
            lblInputField3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/input_field_internet_focused_type.png")));
        }
    }//GEN-LAST:event_txtInputField3KeyTyped

    private void txtInputField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInputField4KeyTyped
        // TODO add your handling code here:
        if ((evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') || (evt.getKeyChar() == '.')) {
            lblInputField4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/input_field_gas_focused_type.png")));
        }
    }//GEN-LAST:event_txtInputField4KeyTyped

    private void txtInputField5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInputField5KeyTyped
        // TODO add your handling code here:
        if ((evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') || (evt.getKeyChar() == '.')) {
            lblInputField5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/input_field_maid_focused_type.png")));
        }
    }//GEN-LAST:event_txtInputField5KeyTyped

    private void txtInputField6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInputField6KeyTyped
        // TODO add your handling code here:
        if ((evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') || (evt.getKeyChar() == '.')) {
            lblInputField6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/input_field_stair_focused_type.png")));
        }
    }//GEN-LAST:event_txtInputField6KeyTyped

    private void txtInputField7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInputField7KeyTyped
        // TODO add your handling code here:
        if ((evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') || (evt.getKeyChar() == '.')) {
            lblInputField7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/input_field_welfare_focused_type.png")));
        }
    }//GEN-LAST:event_txtInputField7KeyTyped

    private void txtInputField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtInputField1FocusLost
        // TODO add your handling code here:
        lblInputField1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/input_field_1.png")));
    }//GEN-LAST:event_txtInputField1FocusLost

    private void txtInputField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtInputField2FocusLost
        // TODO add your handling code here:
        lblInputField2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/input_field_1.png")));
    }//GEN-LAST:event_txtInputField2FocusLost

    private void txtInputField3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtInputField3FocusLost
        // TODO add your handling code here:
        lblInputField3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/input_field_1.png")));
    }//GEN-LAST:event_txtInputField3FocusLost

    private void txtInputField4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtInputField4FocusLost
        // TODO add your handling code here:
        lblInputField4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/input_field_1.png")));
    }//GEN-LAST:event_txtInputField4FocusLost

    private void txtInputField5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtInputField5FocusLost
        // TODO add your handling code here:
        lblInputField5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/input_field_1.png")));
    }//GEN-LAST:event_txtInputField5FocusLost

    private void txtInputField6FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtInputField6FocusLost
        // TODO add your handling code here:
        lblInputField6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/input_field_1.png")));
    }//GEN-LAST:event_txtInputField6FocusLost

    private void txtInputField7FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtInputField7FocusLost
        // TODO add your handling code here:
        lblInputField7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/input_field_1.png")));
    }//GEN-LAST:event_txtInputField7FocusLost

    private void txtInputField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtInputField1FocusGained
        // TODO add your handling code here:
        if ("".equals(txtInputField1.getText())) {
            lblInputField1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/input_field_1_focused.png")));

        } else {
            lblInputField1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/input_field_electricity_focused_type.png")));
        }
    }//GEN-LAST:event_txtInputField1FocusGained

    private void txtInputField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtInputField2FocusGained
        // TODO add your handling code here:
        if ("".equals(txtInputField2.getText())) {
            lblInputField2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/input_field_1_focused.png")));

        } else {
            lblInputField2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/input_field_water_focused_type.png")));
        }
    }//GEN-LAST:event_txtInputField2FocusGained

    private void txtInputField3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtInputField3FocusGained
        // TODO add your handling code here:
        if ("".equals(txtInputField3.getText())) {
            lblInputField3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/input_field_1_focused.png")));

        } else {
            lblInputField3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/input_field_internet_focused_type.png")));
        }
    }//GEN-LAST:event_txtInputField3FocusGained

    private void txtInputField4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtInputField4FocusGained
        // TODO add your handling code here:
        if ("".equals(txtInputField4.getText())) {
            lblInputField4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/input_field_1_focused.png")));

        } else {
            lblInputField4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/input_field_gas_focused_type.png")));
        }
    }//GEN-LAST:event_txtInputField4FocusGained

    private void txtInputField5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtInputField5FocusGained
        // TODO add your handling code here:
        if ("".equals(txtInputField5.getText())) {
            lblInputField5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/input_field_1_focused.png")));

        } else {
            lblInputField5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/input_field_maid_focused_type.png")));
        }
    }//GEN-LAST:event_txtInputField5FocusGained

    private void txtInputField6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtInputField6FocusGained
        // TODO add your handling code here:
        if ("".equals(txtInputField6.getText())) {
            lblInputField6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/input_field_1_focused.png")));

        } else {
            lblInputField6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/input_field_stair_focused_type.png")));
        }
    }//GEN-LAST:event_txtInputField6FocusGained

    private void txtInputField7FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtInputField7FocusGained
        // TODO add your handling code here:
        if ("".equals(txtInputField7.getText())) {
            lblInputField7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/input_field_1_focused.png")));

        } else {
            lblInputField7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theanasuddin/bros/images/input_field_welfare_focused_type.png")));
        }
    }//GEN-LAST:event_txtInputField7FocusGained

    private void lblNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNextMouseClicked
        // TODO add your handling code here:
        if (lblNextEnabled) {
            this.dispose();
//            constructPnlUtilityBill();

            pnlInsideCarousel object = new pnlInsideCarousel();
            object.lblItemOne.setText("Electricity");
            object.lblItemTwo.setText("Internet");
            object.lblItemThree.setText("Gas");
            object.lblItemFour.setText("Water");
            object.lblItemFive.setText("Maid");
            object.lblItemOneValue.setText(String.format("%.2f", electricityBill));
            object.lblItemTwoValue.setText(String.format("%.2f", internetBill));
            object.lblItemThreeValue.setText(String.format("%.2f", gasBill));
            object.lblItemFourValue.setText(String.format("%.2f", waterBill));
            object.lblItemFiveValue.setText(String.format("%.2f", housemaidBill));
            pnlInsideCarousel objectTwo = new pnlInsideCarousel();
            objectTwo.lblItemOne.setText("Stairs");
            objectTwo.lblItemTwo.setText("Welfare");
            objectTwo.lblItemOneValue.setText(String.format("%.2f", stairCleaningBill));
            objectTwo.lblItemTwoValue.setText(String.format("%.2f", welfareAssociationBill));

            DisplayOutput output = new DisplayOutput();
            output.pnlUtilityBillContainer.add(output.lblUtilityBillLeft, object);
            output.pnlUtilityBillContainer.add(output.lblUtilityBillRight, objectTwo);
            totalUtilityBill = getTotalUtilityBill();
            totalHomeRent = getTotalHomeRent();
            individualUtilityBill = getIndividualUtilityBill();
            totalMeal = getTotalMeal();
            totalBazaar = getTotalBazaar();
            output.lblMealValue.setText(String.format("%.2f", totalMeal));
            output.lblBazaarValue.setText(String.format("%.2f", totalBazaar));
            output.lblMealRateValue.setText(String.format("%.2f", totalBazaar / totalMeal));
            output.lblHighestMealValue.setText(getHighestMealHolder());
            output.lblTotalUtilityBillValue.setText(String.format("%.2f", totalUtilityBill));
            output.lblTotalHomeRentValue.setText(String.format("%.2f", totalHomeRent));
            output.lblIndividualUtilityBillValue.setText(String.format("%.2f", individualUtilityBill));
            //pnlInsideCarousel for Home Rent
            int carouselAmountForHomeRent = (int) Math.ceil((double) GetBrosNumber.numberOfMembersField / (double) 5);

            pnlInsideCarouselDynamic[] pnlInsideCarouselDynamicObject = new pnlInsideCarouselDynamic[carouselAmountForHomeRent];
            for (int i = 0; i < carouselAmountForHomeRent; i++) {
                pnlInsideCarouselDynamicObject[i] = new pnlInsideCarouselDynamic();
                for (int j = 0; j < 5; j++) {
                    pnlInsideCarouselDynamicObject[i].lblItem[j].setText(GetBrosDetails.membersName.get(arrayListCounter));
                    pnlInsideCarouselDynamicObject[i].lblItemValue[j].setText(String.format("%.2f", GetBrosDetails.individualHomeRent.get(arrayListCounter)));
                    arrayListCounter++;
                    if (arrayListCounter == GetBrosDetails.membersName.size()) {
                        break;
                    }

                }

            }
            output.pnlHomeRentContainer.add(output.lblHomeRentLeft, pnlInsideCarouselDynamicObject[0]);

            if (carouselAmountForHomeRent == 2) {
                output.pnlHomeRentContainer.add(output.lblHomeRentRight, pnlInsideCarouselDynamicObject[1]);
            }
            //individual utility bill
            pnlInsideCarouselDynamic[] pnlInsideCarouselDynamicObjectIUB = new pnlInsideCarouselDynamic[carouselAmountForHomeRent];
            arrayListCounter = 0;
            for (int i = 0; i < carouselAmountForHomeRent; i++) {
                pnlInsideCarouselDynamicObjectIUB[i] = new pnlInsideCarouselDynamic();
                for (int j = 0; j < 5; j++) {
                    pnlInsideCarouselDynamicObjectIUB[i].lblItem[j].setText(GetBrosDetails.membersName.get(arrayListCounter));
                    pnlInsideCarouselDynamicObjectIUB[i].lblItemValue[j].setText(String.format("%.2f", individualUtilityBill));
                    arrayListCounter++;
                    if (arrayListCounter == GetBrosDetails.membersName.size()) {
                        break;
                    }

                }

            }
            output.pnlIndividualUtilityBillContainer.add(output.lblIndividualUtilityBillLeft, pnlInsideCarouselDynamicObjectIUB[0]);

            if (carouselAmountForHomeRent == 2) {
                output.pnlIndividualUtilityBillContainer.add(output.lblIndividualUtilityBillRight, pnlInsideCarouselDynamicObjectIUB[1]);
            }
            //individual home rent plus utility bill

            pnlInsideCarouselDynamic[] pnlInsideCarouselDynamicObjectIHRUB = new pnlInsideCarouselDynamic[carouselAmountForHomeRent];
            arrayListCounter = 0;
            for (int i = 0; i < carouselAmountForHomeRent; i++) {
                pnlInsideCarouselDynamicObjectIHRUB[i] = new pnlInsideCarouselDynamic();
                for (int j = 0; j < 5; j++) {
                    pnlInsideCarouselDynamicObjectIHRUB[i].lblItem[j].setText(GetBrosDetails.membersName.get(arrayListCounter));
                    pnlInsideCarouselDynamicObjectIHRUB[i].lblItemValue[j].setText(String.format("%.2f", individualUtilityBill + GetBrosDetails.individualHomeRent.get(arrayListCounter)));
                    arrayListCounter++;
                    if (arrayListCounter == GetBrosDetails.membersName.size()) {
                        break;
                    }

                }

            }
            output.pnlIndividualHomeRentUtilityBillContainer.add(output.lblIndividualHomeRentUtilityBillLeft, pnlInsideCarouselDynamicObjectIHRUB[0]);

            if (carouselAmountForHomeRent == 2) {
                output.pnlIndividualHomeRentUtilityBillContainer.add(output.lblIndividualHomeRentUtilityBillRight, pnlInsideCarouselDynamicObjectIHRUB[1]);
            }
            //individual meal expanses
            pnlInsideCarouselDynamicIndividual[] pnlInsideCarouselDynamicIndividualObject = new pnlInsideCarouselDynamicIndividual[GetBrosNumber.numberOfMembersField];
            arrayListCounter = 0;
            for (int i = 0; i < GetBrosNumber.numberOfMembersField; i++) {
                pnlInsideCarouselDynamicIndividualObject[i] = new pnlInsideCarouselDynamicIndividual();
                pnlInsideCarouselDynamicIndividualObject[i].lblName.setText(GetBrosDetails.membersName.get(i));
                pnlInsideCarouselDynamicIndividualObject[i].lblItemTwoValue.setText(String.format("%.2f", GetBrosDetails.individualBazaar.get(i)));
                pnlInsideCarouselDynamicIndividualObject[i].lblItemThreeValue.setText(String.format("%.2f", GetBrosDetails.individualMeal.get(i)));
                pnlInsideCarouselDynamicIndividualObject[i].lblItemFourValue.setText(String.format("%.2f", GetBrosDetails.individualMeal.get(i) * (totalBazaar / totalMeal)));
                pnlInsideCarouselDynamicIndividualObject[i].lblItemFiveValue.setText(String.format("%.2f", Math.abs(GetBrosDetails.individualBazaar.get(i) - (GetBrosDetails.individualMeal.get(i) * (totalBazaar / totalMeal)))));
                
                if((GetBrosDetails.individualBazaar.get(i) - (GetBrosDetails.individualMeal.get(i) * (totalBazaar / totalMeal))) <= 0){
                    pnlInsideCarouselDynamicIndividualObject[i].lblItemFive.setText("Debt");
                }
                else if((GetBrosDetails.individualBazaar.get(i) - (GetBrosDetails.individualMeal.get(i) * (totalBazaar / totalMeal))) > 0){
                    pnlInsideCarouselDynamicIndividualObject[i].lblItemFive.setText("Credit");
                }

            }
            output.pnlIndividualMealExpansesContainer.add(output.lblIndividualMealExpansesLeft, pnlInsideCarouselDynamicIndividualObject[0]);
            if(GetBrosNumber.numberOfMembersField == 2){
                output.pnlIndividualMealExpansesContainer.add(output.lblIndividualMealExpansesRight, pnlInsideCarouselDynamicIndividualObject[1]);
            }

            output.setVisible(true);
        }
    }//GEN-LAST:event_lblNextMouseClicked

    private void txtInputField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInputField1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' || Character.isISOControl(evt.getKeyChar())
                || (evt.getKeyCode() == KeyEvent.VK_CONTROL) || (evt.getKeyCode() == KeyEvent.VK_SHIFT) || (evt.getKeyCode() == KeyEvent.VK_CAPS_LOCK)
                || (evt.getKeyCode() == KeyEvent.VK_COMMAND) || (evt.getKeyCode() == KeyEvent.VK_WINDOWS) || (evt.getKeyCode() == KeyEvent.VK_ALT)
                || (evt.getKeyCode() == KeyEvent.VK_ALT_GRAPH) || (evt.getKeyCode() == KeyEvent.VK_NUM_LOCK) || (evt.getKeyCode() == KeyEvent.VK_HOME)
                || (evt.getKeyCode() == KeyEvent.VK_END) || (evt.getKeyCode() == KeyEvent.VK_LEFT) || (evt.getKeyCode() == KeyEvent.VK_RIGHT) || (evt.getKeyCode() == KeyEvent.VK_DECIMAL)) {
            txtInputField1.setEditable(true);
        } else {
            txtInputField1.setEditable(false);
            getToolkit().beep();

        }
    }//GEN-LAST:event_txtInputField1KeyPressed

    private void txtInputField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInputField2KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' || Character.isISOControl(evt.getKeyChar())
                || (evt.getKeyCode() == KeyEvent.VK_CONTROL) || (evt.getKeyCode() == KeyEvent.VK_SHIFT) || (evt.getKeyCode() == KeyEvent.VK_CAPS_LOCK)
                || (evt.getKeyCode() == KeyEvent.VK_COMMAND) || (evt.getKeyCode() == KeyEvent.VK_WINDOWS) || (evt.getKeyCode() == KeyEvent.VK_ALT)
                || (evt.getKeyCode() == KeyEvent.VK_ALT_GRAPH) || (evt.getKeyCode() == KeyEvent.VK_NUM_LOCK) || (evt.getKeyCode() == KeyEvent.VK_HOME)
                || (evt.getKeyCode() == KeyEvent.VK_END) || (evt.getKeyCode() == KeyEvent.VK_LEFT) || (evt.getKeyCode() == KeyEvent.VK_RIGHT) || (evt.getKeyCode() == KeyEvent.VK_DECIMAL)) {
            txtInputField2.setEditable(true);
        } else {
            txtInputField2.setEditable(false);
            getToolkit().beep();

        }
    }//GEN-LAST:event_txtInputField2KeyPressed

    private void txtInputField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInputField3KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' || Character.isISOControl(evt.getKeyChar())
                || (evt.getKeyCode() == KeyEvent.VK_CONTROL) || (evt.getKeyCode() == KeyEvent.VK_SHIFT) || (evt.getKeyCode() == KeyEvent.VK_CAPS_LOCK)
                || (evt.getKeyCode() == KeyEvent.VK_COMMAND) || (evt.getKeyCode() == KeyEvent.VK_WINDOWS) || (evt.getKeyCode() == KeyEvent.VK_ALT)
                || (evt.getKeyCode() == KeyEvent.VK_ALT_GRAPH) || (evt.getKeyCode() == KeyEvent.VK_NUM_LOCK) || (evt.getKeyCode() == KeyEvent.VK_HOME)
                || (evt.getKeyCode() == KeyEvent.VK_END) || (evt.getKeyCode() == KeyEvent.VK_LEFT) || (evt.getKeyCode() == KeyEvent.VK_RIGHT) || (evt.getKeyCode() == KeyEvent.VK_DECIMAL)) {
            txtInputField3.setEditable(true);
        } else {
            txtInputField3.setEditable(false);
            getToolkit().beep();

        }
    }//GEN-LAST:event_txtInputField3KeyPressed

    private void txtInputField4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInputField4KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' || Character.isISOControl(evt.getKeyChar())
                || (evt.getKeyCode() == KeyEvent.VK_CONTROL) || (evt.getKeyCode() == KeyEvent.VK_SHIFT) || (evt.getKeyCode() == KeyEvent.VK_CAPS_LOCK)
                || (evt.getKeyCode() == KeyEvent.VK_COMMAND) || (evt.getKeyCode() == KeyEvent.VK_WINDOWS) || (evt.getKeyCode() == KeyEvent.VK_ALT)
                || (evt.getKeyCode() == KeyEvent.VK_ALT_GRAPH) || (evt.getKeyCode() == KeyEvent.VK_NUM_LOCK) || (evt.getKeyCode() == KeyEvent.VK_HOME)
                || (evt.getKeyCode() == KeyEvent.VK_END) || (evt.getKeyCode() == KeyEvent.VK_LEFT) || (evt.getKeyCode() == KeyEvent.VK_RIGHT) || (evt.getKeyCode() == KeyEvent.VK_DECIMAL)) {
            txtInputField4.setEditable(true);
        } else {
            txtInputField4.setEditable(false);
            getToolkit().beep();

        }
    }//GEN-LAST:event_txtInputField4KeyPressed

    private void txtInputField5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInputField5KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' || Character.isISOControl(evt.getKeyChar())
                || (evt.getKeyCode() == KeyEvent.VK_CONTROL) || (evt.getKeyCode() == KeyEvent.VK_SHIFT) || (evt.getKeyCode() == KeyEvent.VK_CAPS_LOCK)
                || (evt.getKeyCode() == KeyEvent.VK_COMMAND) || (evt.getKeyCode() == KeyEvent.VK_WINDOWS) || (evt.getKeyCode() == KeyEvent.VK_ALT)
                || (evt.getKeyCode() == KeyEvent.VK_ALT_GRAPH) || (evt.getKeyCode() == KeyEvent.VK_NUM_LOCK) || (evt.getKeyCode() == KeyEvent.VK_HOME)
                || (evt.getKeyCode() == KeyEvent.VK_END) || (evt.getKeyCode() == KeyEvent.VK_LEFT) || (evt.getKeyCode() == KeyEvent.VK_RIGHT) || (evt.getKeyCode() == KeyEvent.VK_DECIMAL)) {
            txtInputField5.setEditable(true);
        } else {
            txtInputField5.setEditable(false);
            getToolkit().beep();

        }
    }//GEN-LAST:event_txtInputField5KeyPressed

    private void txtInputField6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInputField6KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' || Character.isISOControl(evt.getKeyChar())
                || (evt.getKeyCode() == KeyEvent.VK_CONTROL) || (evt.getKeyCode() == KeyEvent.VK_SHIFT) || (evt.getKeyCode() == KeyEvent.VK_CAPS_LOCK)
                || (evt.getKeyCode() == KeyEvent.VK_COMMAND) || (evt.getKeyCode() == KeyEvent.VK_WINDOWS) || (evt.getKeyCode() == KeyEvent.VK_ALT)
                || (evt.getKeyCode() == KeyEvent.VK_ALT_GRAPH) || (evt.getKeyCode() == KeyEvent.VK_NUM_LOCK) || (evt.getKeyCode() == KeyEvent.VK_HOME)
                || (evt.getKeyCode() == KeyEvent.VK_END) || (evt.getKeyCode() == KeyEvent.VK_LEFT) || (evt.getKeyCode() == KeyEvent.VK_RIGHT) || (evt.getKeyCode() == KeyEvent.VK_DECIMAL)) {
            txtInputField6.setEditable(true);
        } else {
            txtInputField6.setEditable(false);
            getToolkit().beep();

        }
    }//GEN-LAST:event_txtInputField6KeyPressed

    private void txtInputField7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInputField7KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' || Character.isISOControl(evt.getKeyChar())
                || (evt.getKeyCode() == KeyEvent.VK_CONTROL) || (evt.getKeyCode() == KeyEvent.VK_SHIFT) || (evt.getKeyCode() == KeyEvent.VK_CAPS_LOCK)
                || (evt.getKeyCode() == KeyEvent.VK_COMMAND) || (evt.getKeyCode() == KeyEvent.VK_WINDOWS) || (evt.getKeyCode() == KeyEvent.VK_ALT)
                || (evt.getKeyCode() == KeyEvent.VK_ALT_GRAPH) || (evt.getKeyCode() == KeyEvent.VK_NUM_LOCK) || (evt.getKeyCode() == KeyEvent.VK_HOME)
                || (evt.getKeyCode() == KeyEvent.VK_END) || (evt.getKeyCode() == KeyEvent.VK_LEFT) || (evt.getKeyCode() == KeyEvent.VK_RIGHT) || (evt.getKeyCode() == KeyEvent.VK_DECIMAL)) {
            txtInputField7.setEditable(true);
        } else {
            txtInputField7.setEditable(false);
            getToolkit().beep();

        }
    }//GEN-LAST:event_txtInputField7KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GetOtherBills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GetOtherBills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GetOtherBills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GetOtherBills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GetOtherBills().setVisible(true);
            }
        });
    }
    static boolean lblNextEnabled = false;
    static boolean lblNextEnabled1 = false;
    static boolean lblNextEnabled2 = false;
    static boolean lblNextEnabled3 = false;
    static boolean lblNextEnabled4 = false;
    static boolean lblNextEnabled5 = false;
    static boolean lblNextEnabled6 = false;
    static boolean lblNextEnabled7 = false;

    public boolean isLong(String str) {
        try {
            Long.parseLong(str);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }

    public boolean isDouble(String str) {
        try {
            Double.parseDouble(str);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }

    static double gasBill;
    static double waterBill;
    static double stairCleaningBill;
    static double welfareAssociationBill;
    static double housemaidBill;
    static double internetBill;
    static double electricityBill;
    static double totalUtilityBill = 0;
    static double individualUtilityBill = 0;
    static double totalHomeRent = 0;
    static double totalMeal = 0;
    static double totalBazaar = 0;
    static int arrayListCounter = 0;

    public double getTotalUtilityBill() {
        double totalUtilityBill;
        totalUtilityBill = gasBill + waterBill + stairCleaningBill + welfareAssociationBill + housemaidBill + internetBill + electricityBill;
        return totalUtilityBill;
    }

    public double getIndividualUtilityBill() {
        double individualUtilityBill;
        individualUtilityBill = totalUtilityBill / GetBrosNumber.numberOfMembersField;
        return individualUtilityBill;
    }

    public double getTotalHomeRent() {
        double totalHomeRent = 0;
        for (double individualHomeRent : GetBrosDetails.individualHomeRent) {
            totalHomeRent = totalHomeRent + individualHomeRent;
        }
        return totalHomeRent;
    }

    public double getTotalMeal() {
        double totalMeal = 0;
        for (double individualMeal : GetBrosDetails.individualMeal) {
            totalMeal = totalMeal + individualMeal;
        }
        return totalMeal;
    }

    public double getTotalBazaar() {
        double totalBazaar = 0;
        for (double individualBazaar : GetBrosDetails.individualBazaar) {
            totalBazaar = totalBazaar + individualBazaar;
        }
        return totalBazaar;
    }

    public String getHighestMealHolder() {
        return GetBrosDetails.membersName.get(GetBrosDetails.individualMeal.indexOf(Collections.max(GetBrosDetails.individualMeal)));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBackGroundImage;
    private javax.swing.JLabel lblInputField1;
    private javax.swing.JLabel lblInputField2;
    private javax.swing.JLabel lblInputField3;
    private javax.swing.JLabel lblInputField4;
    private javax.swing.JLabel lblInputField5;
    private javax.swing.JLabel lblInputField6;
    private javax.swing.JLabel lblInputField7;
    private javax.swing.JLabel lblNext;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JTextField txtInputField1;
    private javax.swing.JTextField txtInputField1Disabled;
    private javax.swing.JTextField txtInputField2;
    private javax.swing.JTextField txtInputField2Disabled;
    private javax.swing.JTextField txtInputField3;
    private javax.swing.JTextField txtInputField3Disabled;
    private javax.swing.JTextField txtInputField4;
    private javax.swing.JTextField txtInputField4Disabled;
    private javax.swing.JTextField txtInputField5;
    private javax.swing.JTextField txtInputField5Disabled;
    private javax.swing.JTextField txtInputField6;
    private javax.swing.JTextField txtInputField6Disabled;
    private javax.swing.JTextField txtInputField7;
    private javax.swing.JTextField txtInputField7Disabled;
    // End of variables declaration//GEN-END:variables
}
